// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_msg.proto

package pb_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enum_SvrTipType int32

const (
	Enum_SvrTipType_MSG   Enum_SvrTipType = 0
	Enum_SvrTipType_WARN  Enum_SvrTipType = 1
	Enum_SvrTipType_ERROR Enum_SvrTipType = 2
)

var Enum_SvrTipType_name = map[int32]string{
	0: "MSG",
	1: "WARN",
	2: "ERROR",
}

var Enum_SvrTipType_value = map[string]int32{
	"MSG":   0,
	"WARN":  1,
	"ERROR": 2,
}

func (x Enum_SvrTipType) Enum() *Enum_SvrTipType {
	p := new(Enum_SvrTipType)
	*p = x
	return p
}

func (x Enum_SvrTipType) String() string {
	return proto.EnumName(Enum_SvrTipType_name, int32(x))
}

func (x *Enum_SvrTipType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_SvrTipType_value, data, "Enum_SvrTipType")
	if err != nil {
		return err
	}
	*x = Enum_SvrTipType(value)
	return nil
}

func (Enum_SvrTipType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{0}
}

// 牌花色
type Enum_CardKind int32

const (
	Enum_CardKind_NONE    Enum_CardKind = 0
	Enum_CardKind_DIAMOND Enum_CardKind = 1
	Enum_CardKind_CLUBS   Enum_CardKind = 2
	Enum_CardKind_HEART   Enum_CardKind = 3
	Enum_CardKind_SPADE   Enum_CardKind = 4
)

var Enum_CardKind_name = map[int32]string{
	0: "NONE",
	1: "DIAMOND",
	2: "CLUBS",
	3: "HEART",
	4: "SPADE",
}

var Enum_CardKind_value = map[string]int32{
	"NONE":    0,
	"DIAMOND": 1,
	"CLUBS":   2,
	"HEART":   3,
	"SPADE":   4,
}

func (x Enum_CardKind) Enum() *Enum_CardKind {
	p := new(Enum_CardKind)
	*p = x
	return p
}

func (x Enum_CardKind) String() string {
	return proto.EnumName(Enum_CardKind_name, int32(x))
}

func (x *Enum_CardKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_CardKind_value, data, "Enum_CardKind")
	if err != nil {
		return err
	}
	*x = Enum_CardKind(value)
	return nil
}

func (Enum_CardKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{1}
}

// 牌型
type Enum_CardSuit int32

const (
	Enum_CardSuit_NULL Enum_CardSuit = 0
	// 高牌
	Enum_CardSuit_HIGH_CARD Enum_CardSuit = 1
	// 一对
	Enum_CardSuit_ONE_PAIR Enum_CardSuit = 2
	// 两对
	Enum_CardSuit_TWO_PAIRS Enum_CardSuit = 3
	// 三条
	Enum_CardSuit_THREE_OF_A_KIND Enum_CardSuit = 4
	// 顺子
	Enum_CardSuit_STRAIGHT Enum_CardSuit = 5
	// 同花
	Enum_CardSuit_FLUSH Enum_CardSuit = 6
	// 葫芦
	Enum_CardSuit_FULL_HOUSE Enum_CardSuit = 7
	// 四条
	Enum_CardSuit_FOUR_OF_A_KIND Enum_CardSuit = 8
	// 同花顺
	Enum_CardSuit_STRAIGHT_FLUSH Enum_CardSuit = 9
	// 皇家同花顺
	Enum_CardSuit_ROYAL_FLUSH Enum_CardSuit = 10
)

var Enum_CardSuit_name = map[int32]string{
	0:  "NULL",
	1:  "HIGH_CARD",
	2:  "ONE_PAIR",
	3:  "TWO_PAIRS",
	4:  "THREE_OF_A_KIND",
	5:  "STRAIGHT",
	6:  "FLUSH",
	7:  "FULL_HOUSE",
	8:  "FOUR_OF_A_KIND",
	9:  "STRAIGHT_FLUSH",
	10: "ROYAL_FLUSH",
}

var Enum_CardSuit_value = map[string]int32{
	"NULL":            0,
	"HIGH_CARD":       1,
	"ONE_PAIR":        2,
	"TWO_PAIRS":       3,
	"THREE_OF_A_KIND": 4,
	"STRAIGHT":        5,
	"FLUSH":           6,
	"FULL_HOUSE":      7,
	"FOUR_OF_A_KIND":  8,
	"STRAIGHT_FLUSH":  9,
	"ROYAL_FLUSH":     10,
}

func (x Enum_CardSuit) Enum() *Enum_CardSuit {
	p := new(Enum_CardSuit)
	*p = x
	return p
}

func (x Enum_CardSuit) String() string {
	return proto.EnumName(Enum_CardSuit_name, int32(x))
}

func (x *Enum_CardSuit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_CardSuit_value, data, "Enum_CardSuit")
	if err != nil {
		return err
	}
	*x = Enum_CardSuit(value)
	return nil
}

func (Enum_CardSuit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{2}
}

// 玩家操作类型
type Enum_ActionOptions int32

const (
	Enum_ActionOptions_ACT_FOLD  Enum_ActionOptions = 0
	Enum_ActionOptions_ACT_CALL  Enum_ActionOptions = 1
	Enum_ActionOptions_ACT_RAISE Enum_ActionOptions = 2
	Enum_ActionOptions_ACT_CHECK Enum_ActionOptions = 3
)

var Enum_ActionOptions_name = map[int32]string{
	0: "ACT_FOLD",
	1: "ACT_CALL",
	2: "ACT_RAISE",
	3: "ACT_CHECK",
}

var Enum_ActionOptions_value = map[string]int32{
	"ACT_FOLD":  0,
	"ACT_CALL":  1,
	"ACT_RAISE": 2,
	"ACT_CHECK": 3,
}

func (x Enum_ActionOptions) Enum() *Enum_ActionOptions {
	p := new(Enum_ActionOptions)
	*p = x
	return p
}

func (x Enum_ActionOptions) String() string {
	return proto.EnumName(Enum_ActionOptions_name, int32(x))
}

func (x *Enum_ActionOptions) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_ActionOptions_value, data, "Enum_ActionOptions")
	if err != nil {
		return err
	}
	*x = Enum_ActionOptions(value)
	return nil
}

func (Enum_ActionOptions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{3}
}

// 盲注类型
type Enum_Blind int32

const (
	Enum_Blind_NO_BLIND    Enum_Blind = 0
	Enum_Blind_SMALL_BLIND Enum_Blind = 1
	Enum_Blind_BIG_BLIND   Enum_Blind = 2
)

var Enum_Blind_name = map[int32]string{
	0: "NO_BLIND",
	1: "SMALL_BLIND",
	2: "BIG_BLIND",
}

var Enum_Blind_value = map[string]int32{
	"NO_BLIND":    0,
	"SMALL_BLIND": 1,
	"BIG_BLIND":   2,
}

func (x Enum_Blind) Enum() *Enum_Blind {
	p := new(Enum_Blind)
	*p = x
	return p
}

func (x Enum_Blind) String() string {
	return proto.EnumName(Enum_Blind_name, int32(x))
}

func (x *Enum_Blind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_Blind_value, data, "Enum_Blind")
	if err != nil {
		return err
	}
	*x = Enum_Blind(value)
	return nil
}

func (Enum_Blind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{4}
}

// 游戏阶段
type Enum_GameStep int32

const (
	Enum_GameStep_STEP_WAITING   Enum_GameStep = 0
	Enum_GameStep_STEP_PRE_FLOP  Enum_GameStep = 1
	Enum_GameStep_STEP_FLOP      Enum_GameStep = 2
	Enum_GameStep_STEP_TURN      Enum_GameStep = 3
	Enum_GameStep_STEP_RIVER     Enum_GameStep = 4
	Enum_GameStep_STEP_SHOW_DOWN Enum_GameStep = 5
)

var Enum_GameStep_name = map[int32]string{
	0: "STEP_WAITING",
	1: "STEP_PRE_FLOP",
	2: "STEP_FLOP",
	3: "STEP_TURN",
	4: "STEP_RIVER",
	5: "STEP_SHOW_DOWN",
}

var Enum_GameStep_value = map[string]int32{
	"STEP_WAITING":   0,
	"STEP_PRE_FLOP":  1,
	"STEP_FLOP":      2,
	"STEP_TURN":      3,
	"STEP_RIVER":     4,
	"STEP_SHOW_DOWN": 5,
}

func (x Enum_GameStep) Enum() *Enum_GameStep {
	p := new(Enum_GameStep)
	*p = x
	return p
}

func (x Enum_GameStep) String() string {
	return proto.EnumName(Enum_GameStep_name, int32(x))
}

func (x *Enum_GameStep) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_GameStep_value, data, "Enum_GameStep")
	if err != nil {
		return err
	}
	*x = Enum_GameStep(value)
	return nil
}

func (Enum_GameStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{5}
}

// 本轮玩家表态
type Enum_PlayerStatus int32

const (
	Enum_PlayerStatus_STATUS_WAITING   Enum_PlayerStatus = 0
	Enum_PlayerStatus_STATUS_RAISE     Enum_PlayerStatus = 1
	Enum_PlayerStatus_STATUS_CALL      Enum_PlayerStatus = 2
	Enum_PlayerStatus_STATUS_CHECK     Enum_PlayerStatus = 3
	Enum_PlayerStatus_STATUS_FOLD      Enum_PlayerStatus = 4
	Enum_PlayerStatus_STATUS_SHOW_DOWN Enum_PlayerStatus = 5
)

var Enum_PlayerStatus_name = map[int32]string{
	0: "STATUS_WAITING",
	1: "STATUS_RAISE",
	2: "STATUS_CALL",
	3: "STATUS_CHECK",
	4: "STATUS_FOLD",
	5: "STATUS_SHOW_DOWN",
}

var Enum_PlayerStatus_value = map[string]int32{
	"STATUS_WAITING":   0,
	"STATUS_RAISE":     1,
	"STATUS_CALL":      2,
	"STATUS_CHECK":     3,
	"STATUS_FOLD":      4,
	"STATUS_SHOW_DOWN": 5,
}

func (x Enum_PlayerStatus) Enum() *Enum_PlayerStatus {
	p := new(Enum_PlayerStatus)
	*p = x
	return p
}

func (x Enum_PlayerStatus) String() string {
	return proto.EnumName(Enum_PlayerStatus_name, int32(x))
}

func (x *Enum_PlayerStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_PlayerStatus_value, data, "Enum_PlayerStatus")
	if err != nil {
		return err
	}
	*x = Enum_PlayerStatus(value)
	return nil
}

func (Enum_PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{6}
}

// 游戏中每个玩家行动时间
type Enum_ActionTimeS int32

const (
	Enum_ActionTimeS_XXX    Enum_ActionTimeS = 0
	Enum_ActionTimeS_NORMAL Enum_ActionTimeS = 15
	Enum_ActionTimeS_FAST   Enum_ActionTimeS = 10
)

var Enum_ActionTimeS_name = map[int32]string{
	0:  "XXX",
	15: "NORMAL",
	10: "FAST",
}

var Enum_ActionTimeS_value = map[string]int32{
	"XXX":    0,
	"NORMAL": 15,
	"FAST":   10,
}

func (x Enum_ActionTimeS) Enum() *Enum_ActionTimeS {
	p := new(Enum_ActionTimeS)
	*p = x
	return p
}

func (x Enum_ActionTimeS) String() string {
	return proto.EnumName(Enum_ActionTimeS_name, int32(x))
}

func (x *Enum_ActionTimeS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_ActionTimeS_value, data, "Enum_ActionTimeS")
	if err != nil {
		return err
	}
	*x = Enum_ActionTimeS(value)
	return nil
}

func (Enum_ActionTimeS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{7}
}

//--0
type PingC2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingC2S) Reset()         { *m = PingC2S{} }
func (m *PingC2S) String() string { return proto.CompactTextString(m) }
func (*PingC2S) ProtoMessage()    {}
func (*PingC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{0}
}

func (m *PingC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingC2S.Unmarshal(m, b)
}
func (m *PingC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingC2S.Marshal(b, m, deterministic)
}
func (m *PingC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingC2S.Merge(m, src)
}
func (m *PingC2S) XXX_Size() int {
	return xxx_messageInfo_PingC2S.Size(m)
}
func (m *PingC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PingC2S.DiscardUnknown(m)
}

var xxx_messageInfo_PingC2S proto.InternalMessageInfo

//--1
type PongS2C struct {
	ServerTime           *int64   `protobuf:"varint,1,req,name=serverTime" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongS2C) Reset()         { *m = PongS2C{} }
func (m *PongS2C) String() string { return proto.CompactTextString(m) }
func (*PongS2C) ProtoMessage()    {}
func (*PongS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{1}
}

func (m *PongS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongS2C.Unmarshal(m, b)
}
func (m *PongS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongS2C.Marshal(b, m, deterministic)
}
func (m *PongS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongS2C.Merge(m, src)
}
func (m *PongS2C) XXX_Size() int {
	return xxx_messageInfo_PongS2C.Size(m)
}
func (m *PongS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PongS2C.DiscardUnknown(m)
}

var xxx_messageInfo_PongS2C proto.InternalMessageInfo

func (m *PongS2C) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

//--2
type SvrMsgS2C struct {
	Code                 *int32           `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Data                 *string          `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	TipType              *Enum_SvrTipType `protobuf:"varint,3,req,name=tipType,enum=pb_msg.Enum_SvrTipType" json:"tipType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SvrMsgS2C) Reset()         { *m = SvrMsgS2C{} }
func (m *SvrMsgS2C) String() string { return proto.CompactTextString(m) }
func (*SvrMsgS2C) ProtoMessage()    {}
func (*SvrMsgS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{2}
}

func (m *SvrMsgS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvrMsgS2C.Unmarshal(m, b)
}
func (m *SvrMsgS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvrMsgS2C.Marshal(b, m, deterministic)
}
func (m *SvrMsgS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvrMsgS2C.Merge(m, src)
}
func (m *SvrMsgS2C) XXX_Size() int {
	return xxx_messageInfo_SvrMsgS2C.Size(m)
}
func (m *SvrMsgS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SvrMsgS2C.DiscardUnknown(m)
}

var xxx_messageInfo_SvrMsgS2C proto.InternalMessageInfo

func (m *SvrMsgS2C) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *SvrMsgS2C) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *SvrMsgS2C) GetTipType() Enum_SvrTipType {
	if m != nil && m.TipType != nil {
		return *m.TipType
	}
	return Enum_SvrTipType_MSG
}

// 玩家基础信息
type PlayerInfo struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Face                 *string  `protobuf:"bytes,3,req,name=face" json:"face,omitempty"`
	Balance              *float64 `protobuf:"fixed64,4,req,name=balance" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{3}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PlayerInfo) GetFace() string {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return ""
}

func (m *PlayerInfo) GetBalance() float64 {
	if m != nil && m.Balance != nil {
		return *m.Balance
	}
	return 0
}

// 登录信息
type LoginInfo struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	GameId               *string  `protobuf:"bytes,2,req,name=game_id,json=gameId" json:"game_id,omitempty"`
	ServerUrl            *string  `protobuf:"bytes,3,req,name=server_url,json=serverUrl" json:"server_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{4}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *LoginInfo) GetGameId() string {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return ""
}

func (m *LoginInfo) GetServerUrl() string {
	if m != nil && m.ServerUrl != nil {
		return *m.ServerUrl
	}
	return ""
}

//--3
type LoginC2S struct {
	LoginInfo            *LoginInfo `protobuf:"bytes,1,req,name=loginInfo" json:"loginInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginC2S) Reset()         { *m = LoginC2S{} }
func (m *LoginC2S) String() string { return proto.CompactTextString(m) }
func (*LoginC2S) ProtoMessage()    {}
func (*LoginC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{5}
}

func (m *LoginC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginC2S.Unmarshal(m, b)
}
func (m *LoginC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginC2S.Marshal(b, m, deterministic)
}
func (m *LoginC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginC2S.Merge(m, src)
}
func (m *LoginC2S) XXX_Size() int {
	return xxx_messageInfo_LoginC2S.Size(m)
}
func (m *LoginC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginC2S.DiscardUnknown(m)
}

var xxx_messageInfo_LoginC2S proto.InternalMessageInfo

func (m *LoginC2S) GetLoginInfo() *LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

//--4
type LoginResultS2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResultS2C) Reset()         { *m = LoginResultS2C{} }
func (m *LoginResultS2C) String() string { return proto.CompactTextString(m) }
func (*LoginResultS2C) ProtoMessage()    {}
func (*LoginResultS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{6}
}

func (m *LoginResultS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResultS2C.Unmarshal(m, b)
}
func (m *LoginResultS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResultS2C.Marshal(b, m, deterministic)
}
func (m *LoginResultS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResultS2C.Merge(m, src)
}
func (m *LoginResultS2C) XXX_Size() int {
	return xxx_messageInfo_LoginResultS2C.Size(m)
}
func (m *LoginResultS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResultS2C.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResultS2C proto.InternalMessageInfo

func (m *LoginResultS2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// 牌型数据
type CardSuitData struct {
	HandCardKeys         []int32        `protobuf:"varint,1,rep,name=handCardKeys" json:"handCardKeys,omitempty"`
	PublicCardKeys       []int32        `protobuf:"varint,2,rep,name=publicCardKeys" json:"publicCardKeys,omitempty"`
	SuitPattern          *Enum_CardSuit `protobuf:"varint,3,req,name=suitPattern,enum=pb_msg.Enum_CardSuit" json:"suitPattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CardSuitData) Reset()         { *m = CardSuitData{} }
func (m *CardSuitData) String() string { return proto.CompactTextString(m) }
func (*CardSuitData) ProtoMessage()    {}
func (*CardSuitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{7}
}

func (m *CardSuitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardSuitData.Unmarshal(m, b)
}
func (m *CardSuitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardSuitData.Marshal(b, m, deterministic)
}
func (m *CardSuitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardSuitData.Merge(m, src)
}
func (m *CardSuitData) XXX_Size() int {
	return xxx_messageInfo_CardSuitData.Size(m)
}
func (m *CardSuitData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardSuitData.DiscardUnknown(m)
}

var xxx_messageInfo_CardSuitData proto.InternalMessageInfo

func (m *CardSuitData) GetHandCardKeys() []int32 {
	if m != nil {
		return m.HandCardKeys
	}
	return nil
}

func (m *CardSuitData) GetPublicCardKeys() []int32 {
	if m != nil {
		return m.PublicCardKeys
	}
	return nil
}

func (m *CardSuitData) GetSuitPattern() Enum_CardSuit {
	if m != nil && m.SuitPattern != nil {
		return *m.SuitPattern
	}
	return Enum_CardSuit_NULL
}

// 房间基础信息
type RoomInfo struct {
	RoomId               *string           `protobuf:"bytes,1,opt,name=roomId" json:"roomId,omitempty"`
	CfgId                *string           `protobuf:"bytes,2,req,name=cfgId" json:"cfgId,omitempty"`
	MaxPlayer            *int32            `protobuf:"varint,3,req,name=maxPlayer" json:"maxPlayer,omitempty"`
	ActionTimeS          *Enum_ActionTimeS `protobuf:"varint,4,req,name=actionTime_s,json=actionTimeS,enum=pb_msg.Enum_ActionTimeS" json:"actionTime_s,omitempty"`
	Pwd                  *string           `protobuf:"bytes,5,opt,name=pwd" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{8}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

func (m *RoomInfo) GetCfgId() string {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return ""
}

func (m *RoomInfo) GetMaxPlayer() int32 {
	if m != nil && m.MaxPlayer != nil {
		return *m.MaxPlayer
	}
	return 0
}

func (m *RoomInfo) GetActionTimeS() Enum_ActionTimeS {
	if m != nil && m.ActionTimeS != nil {
		return *m.ActionTimeS
	}
	return Enum_ActionTimeS_XXX
}

func (m *RoomInfo) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

// 玩家数据
type PlayerData struct {
	PlayerInfo           *PlayerInfo        `protobuf:"bytes,1,req,name=playerInfo" json:"playerInfo,omitempty"`
	Position             *int32             `protobuf:"varint,2,req,name=position" json:"position,omitempty"`
	IsRaised             *bool              `protobuf:"varint,3,req,name=isRaised" json:"isRaised,omitempty"`
	PlayerStatus         *Enum_PlayerStatus `protobuf:"varint,4,req,name=playerStatus,enum=pb_msg.Enum_PlayerStatus" json:"playerStatus,omitempty"`
	DropedBets           *float64           `protobuf:"fixed64,5,req,name=dropedBets" json:"dropedBets,omitempty"`
	DropedBetsSum        *float64           `protobuf:"fixed64,6,req,name=dropedBetsSum" json:"dropedBetsSum,omitempty"`
	CardKeys             []int32            `protobuf:"varint,7,rep,name=cardKeys" json:"cardKeys,omitempty"`
	CardSuitData         *CardSuitData      `protobuf:"bytes,8,req,name=cardSuitData" json:"cardSuitData,omitempty"`
	IsWinner             *bool              `protobuf:"varint,9,req,name=isWinner" json:"isWinner,omitempty"`
	Blind                *Enum_Blind        `protobuf:"varint,10,req,name=blind,enum=pb_msg.Enum_Blind" json:"blind,omitempty"`
	IsButton             *bool              `protobuf:"varint,11,req,name=isButton" json:"isButton,omitempty"`
	IsAllIn              *bool              `protobuf:"varint,12,req,name=isAllIn" json:"isAllIn,omitempty"`
	ResultMoney          *float64           `protobuf:"fixed64,13,req,name=resultMoney" json:"resultMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{9}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *PlayerData) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *PlayerData) GetIsRaised() bool {
	if m != nil && m.IsRaised != nil {
		return *m.IsRaised
	}
	return false
}

func (m *PlayerData) GetPlayerStatus() Enum_PlayerStatus {
	if m != nil && m.PlayerStatus != nil {
		return *m.PlayerStatus
	}
	return Enum_PlayerStatus_STATUS_WAITING
}

func (m *PlayerData) GetDropedBets() float64 {
	if m != nil && m.DropedBets != nil {
		return *m.DropedBets
	}
	return 0
}

func (m *PlayerData) GetDropedBetsSum() float64 {
	if m != nil && m.DropedBetsSum != nil {
		return *m.DropedBetsSum
	}
	return 0
}

func (m *PlayerData) GetCardKeys() []int32 {
	if m != nil {
		return m.CardKeys
	}
	return nil
}

func (m *PlayerData) GetCardSuitData() *CardSuitData {
	if m != nil {
		return m.CardSuitData
	}
	return nil
}

func (m *PlayerData) GetIsWinner() bool {
	if m != nil && m.IsWinner != nil {
		return *m.IsWinner
	}
	return false
}

func (m *PlayerData) GetBlind() Enum_Blind {
	if m != nil && m.Blind != nil {
		return *m.Blind
	}
	return Enum_Blind_NO_BLIND
}

func (m *PlayerData) GetIsButton() bool {
	if m != nil && m.IsButton != nil {
		return *m.IsButton
	}
	return false
}

func (m *PlayerData) GetIsAllIn() bool {
	if m != nil && m.IsAllIn != nil {
		return *m.IsAllIn
	}
	return false
}

func (m *PlayerData) GetResultMoney() float64 {
	if m != nil && m.ResultMoney != nil {
		return *m.ResultMoney
	}
	return 0
}

// 房间数据
type RoomData struct {
	RoomInfo             *RoomInfo      `protobuf:"bytes,1,req,name=roomInfo" json:"roomInfo,omitempty"`
	IsStepEnd            *bool          `protobuf:"varint,2,req,name=isStepEnd" json:"isStepEnd,omitempty"`
	GameStep             *Enum_GameStep `protobuf:"varint,3,req,name=gameStep,enum=pb_msg.Enum_GameStep" json:"gameStep,omitempty"`
	MinRaise             *float64       `protobuf:"fixed64,4,req,name=minRaise" json:"minRaise,omitempty"`
	ActivePos            *int32         `protobuf:"varint,5,req,name=activePos" json:"activePos,omitempty"`
	NextStepTs           *int64         `protobuf:"varint,6,req,name=nextStepTs" json:"nextStepTs,omitempty"`
	Pot                  *float64       `protobuf:"fixed64,7,req,name=pot" json:"pot,omitempty"`
	PublicCardKeys       []int32        `protobuf:"varint,8,rep,name=publicCardKeys" json:"publicCardKeys,omitempty"`
	PlayerDatas          []*PlayerData  `protobuf:"bytes,9,rep,name=playerDatas" json:"playerDatas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{10}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

func (m *RoomData) GetIsStepEnd() bool {
	if m != nil && m.IsStepEnd != nil {
		return *m.IsStepEnd
	}
	return false
}

func (m *RoomData) GetGameStep() Enum_GameStep {
	if m != nil && m.GameStep != nil {
		return *m.GameStep
	}
	return Enum_GameStep_STEP_WAITING
}

func (m *RoomData) GetMinRaise() float64 {
	if m != nil && m.MinRaise != nil {
		return *m.MinRaise
	}
	return 0
}

func (m *RoomData) GetActivePos() int32 {
	if m != nil && m.ActivePos != nil {
		return *m.ActivePos
	}
	return 0
}

func (m *RoomData) GetNextStepTs() int64 {
	if m != nil && m.NextStepTs != nil {
		return *m.NextStepTs
	}
	return 0
}

func (m *RoomData) GetPot() float64 {
	if m != nil && m.Pot != nil {
		return *m.Pot
	}
	return 0
}

func (m *RoomData) GetPublicCardKeys() []int32 {
	if m != nil {
		return m.PublicCardKeys
	}
	return nil
}

func (m *RoomData) GetPlayerDatas() []*PlayerData {
	if m != nil {
		return m.PlayerDatas
	}
	return nil
}

//--5 根据房间条件快速匹配一张牌桌
type QuickStartC2S struct {
	RoomInfo             *RoomInfo `protobuf:"bytes,1,req,name=roomInfo" json:"roomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QuickStartC2S) Reset()         { *m = QuickStartC2S{} }
func (m *QuickStartC2S) String() string { return proto.CompactTextString(m) }
func (*QuickStartC2S) ProtoMessage()    {}
func (*QuickStartC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{11}
}

func (m *QuickStartC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuickStartC2S.Unmarshal(m, b)
}
func (m *QuickStartC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuickStartC2S.Marshal(b, m, deterministic)
}
func (m *QuickStartC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuickStartC2S.Merge(m, src)
}
func (m *QuickStartC2S) XXX_Size() int {
	return xxx_messageInfo_QuickStartC2S.Size(m)
}
func (m *QuickStartC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_QuickStartC2S.DiscardUnknown(m)
}

var xxx_messageInfo_QuickStartC2S proto.InternalMessageInfo

func (m *QuickStartC2S) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

//--6 创建房间请求
type CreateRoomC2S struct {
	RoomInfo             *RoomInfo `protobuf:"bytes,1,req,name=roomInfo" json:"roomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateRoomC2S) Reset()         { *m = CreateRoomC2S{} }
func (m *CreateRoomC2S) String() string { return proto.CompactTextString(m) }
func (*CreateRoomC2S) ProtoMessage()    {}
func (*CreateRoomC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{12}
}

func (m *CreateRoomC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomC2S.Unmarshal(m, b)
}
func (m *CreateRoomC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomC2S.Marshal(b, m, deterministic)
}
func (m *CreateRoomC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomC2S.Merge(m, src)
}
func (m *CreateRoomC2S) XXX_Size() int {
	return xxx_messageInfo_CreateRoomC2S.Size(m)
}
func (m *CreateRoomC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomC2S.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomC2S proto.InternalMessageInfo

func (m *CreateRoomC2S) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

//--7 加入房间请求
type JoinRoomC2S struct {
	RoomId               *string  `protobuf:"bytes,1,req,name=roomId" json:"roomId,omitempty"`
	Pwd                  *string  `protobuf:"bytes,2,req,name=pwd" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomC2S) Reset()         { *m = JoinRoomC2S{} }
func (m *JoinRoomC2S) String() string { return proto.CompactTextString(m) }
func (*JoinRoomC2S) ProtoMessage()    {}
func (*JoinRoomC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{13}
}

func (m *JoinRoomC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomC2S.Unmarshal(m, b)
}
func (m *JoinRoomC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomC2S.Marshal(b, m, deterministic)
}
func (m *JoinRoomC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomC2S.Merge(m, src)
}
func (m *JoinRoomC2S) XXX_Size() int {
	return xxx_messageInfo_JoinRoomC2S.Size(m)
}
func (m *JoinRoomC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomC2S.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomC2S proto.InternalMessageInfo

func (m *JoinRoomC2S) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

func (m *JoinRoomC2S) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

//--8 进入房间
type EnterRoomS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,req,name=roomData" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnterRoomS2C) Reset()         { *m = EnterRoomS2C{} }
func (m *EnterRoomS2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoomS2C) ProtoMessage()    {}
func (*EnterRoomS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{14}
}

func (m *EnterRoomS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomS2C.Unmarshal(m, b)
}
func (m *EnterRoomS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomS2C.Marshal(b, m, deterministic)
}
func (m *EnterRoomS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomS2C.Merge(m, src)
}
func (m *EnterRoomS2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoomS2C.Size(m)
}
func (m *EnterRoomS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomS2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomS2C proto.InternalMessageInfo

func (m *EnterRoomS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

//--9 退出房间请求
type ExitRoomC2S struct {
	Id                   *string  `protobuf:"bytes,1,req,name=Id" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitRoomC2S) Reset()         { *m = ExitRoomC2S{} }
func (m *ExitRoomC2S) String() string { return proto.CompactTextString(m) }
func (*ExitRoomC2S) ProtoMessage()    {}
func (*ExitRoomC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{15}
}

func (m *ExitRoomC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitRoomC2S.Unmarshal(m, b)
}
func (m *ExitRoomC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitRoomC2S.Marshal(b, m, deterministic)
}
func (m *ExitRoomC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitRoomC2S.Merge(m, src)
}
func (m *ExitRoomC2S) XXX_Size() int {
	return xxx_messageInfo_ExitRoomC2S.Size(m)
}
func (m *ExitRoomC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitRoomC2S.DiscardUnknown(m)
}

var xxx_messageInfo_ExitRoomC2S proto.InternalMessageInfo

func (m *ExitRoomC2S) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

//--10 退出房间
type ExitRoomS2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ExitRoomS2C) Reset()         { *m = ExitRoomS2C{} }
func (m *ExitRoomS2C) String() string { return proto.CompactTextString(m) }
func (*ExitRoomS2C) ProtoMessage()    {}
func (*ExitRoomS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{16}
}

func (m *ExitRoomS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitRoomS2C.Unmarshal(m, b)
}
func (m *ExitRoomS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitRoomS2C.Marshal(b, m, deterministic)
}
func (m *ExitRoomS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitRoomS2C.Merge(m, src)
}
func (m *ExitRoomS2C) XXX_Size() int {
	return xxx_messageInfo_ExitRoomS2C.Size(m)
}
func (m *ExitRoomS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitRoomS2C.DiscardUnknown(m)
}

var xxx_messageInfo_ExitRoomS2C proto.InternalMessageInfo

func (m *ExitRoomS2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

//--11 玩家加入
type OtherPlayerJoinS2C struct {
	PlayerData           *PlayerData `protobuf:"bytes,1,req,name=playerData" json:"playerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OtherPlayerJoinS2C) Reset()         { *m = OtherPlayerJoinS2C{} }
func (m *OtherPlayerJoinS2C) String() string { return proto.CompactTextString(m) }
func (*OtherPlayerJoinS2C) ProtoMessage()    {}
func (*OtherPlayerJoinS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{17}
}

func (m *OtherPlayerJoinS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherPlayerJoinS2C.Unmarshal(m, b)
}
func (m *OtherPlayerJoinS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherPlayerJoinS2C.Marshal(b, m, deterministic)
}
func (m *OtherPlayerJoinS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherPlayerJoinS2C.Merge(m, src)
}
func (m *OtherPlayerJoinS2C) XXX_Size() int {
	return xxx_messageInfo_OtherPlayerJoinS2C.Size(m)
}
func (m *OtherPlayerJoinS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherPlayerJoinS2C.DiscardUnknown(m)
}

var xxx_messageInfo_OtherPlayerJoinS2C proto.InternalMessageInfo

func (m *OtherPlayerJoinS2C) GetPlayerData() *PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

//--12 玩家离场（观战也算离场，只要不在桌上）
type OtherPlayerLeaveS2C struct {
	Position             *int32   `protobuf:"varint,1,req,name=position" json:"position,omitempty"`
	Pot                  *float64 `protobuf:"fixed64,2,req,name=pot" json:"pot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OtherPlayerLeaveS2C) Reset()         { *m = OtherPlayerLeaveS2C{} }
func (m *OtherPlayerLeaveS2C) String() string { return proto.CompactTextString(m) }
func (*OtherPlayerLeaveS2C) ProtoMessage()    {}
func (*OtherPlayerLeaveS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{18}
}

func (m *OtherPlayerLeaveS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherPlayerLeaveS2C.Unmarshal(m, b)
}
func (m *OtherPlayerLeaveS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherPlayerLeaveS2C.Marshal(b, m, deterministic)
}
func (m *OtherPlayerLeaveS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherPlayerLeaveS2C.Merge(m, src)
}
func (m *OtherPlayerLeaveS2C) XXX_Size() int {
	return xxx_messageInfo_OtherPlayerLeaveS2C.Size(m)
}
func (m *OtherPlayerLeaveS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherPlayerLeaveS2C.DiscardUnknown(m)
}

var xxx_messageInfo_OtherPlayerLeaveS2C proto.InternalMessageInfo

func (m *OtherPlayerLeaveS2C) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *OtherPlayerLeaveS2C) GetPot() float64 {
	if m != nil && m.Pot != nil {
		return *m.Pot
	}
	return 0
}

//--13 玩家入座 请求
type SitDownC2S struct {
	Position             *int32   `protobuf:"varint,1,req,name=position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitDownC2S) Reset()         { *m = SitDownC2S{} }
func (m *SitDownC2S) String() string { return proto.CompactTextString(m) }
func (*SitDownC2S) ProtoMessage()    {}
func (*SitDownC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{19}
}

func (m *SitDownC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownC2S.Unmarshal(m, b)
}
func (m *SitDownC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownC2S.Marshal(b, m, deterministic)
}
func (m *SitDownC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownC2S.Merge(m, src)
}
func (m *SitDownC2S) XXX_Size() int {
	return xxx_messageInfo_SitDownC2S.Size(m)
}
func (m *SitDownC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownC2S.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownC2S proto.InternalMessageInfo

func (m *SitDownC2S) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

//--14 玩家入座
type SitDownS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,req,name=roomData" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SitDownS2C) Reset()         { *m = SitDownS2C{} }
func (m *SitDownS2C) String() string { return proto.CompactTextString(m) }
func (*SitDownS2C) ProtoMessage()    {}
func (*SitDownS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{20}
}

func (m *SitDownS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownS2C.Unmarshal(m, b)
}
func (m *SitDownS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownS2C.Marshal(b, m, deterministic)
}
func (m *SitDownS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownS2C.Merge(m, src)
}
func (m *SitDownS2C) XXX_Size() int {
	return xxx_messageInfo_SitDownS2C.Size(m)
}
func (m *SitDownS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownS2C.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownS2C proto.InternalMessageInfo

func (m *SitDownS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

//--15 玩家离座观战 请求
type StandUpC2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandUpC2S) Reset()         { *m = StandUpC2S{} }
func (m *StandUpC2S) String() string { return proto.CompactTextString(m) }
func (*StandUpC2S) ProtoMessage()    {}
func (*StandUpC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{21}
}

func (m *StandUpC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandUpC2S.Unmarshal(m, b)
}
func (m *StandUpC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandUpC2S.Marshal(b, m, deterministic)
}
func (m *StandUpC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandUpC2S.Merge(m, src)
}
func (m *StandUpC2S) XXX_Size() int {
	return xxx_messageInfo_StandUpC2S.Size(m)
}
func (m *StandUpC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_StandUpC2S.DiscardUnknown(m)
}

var xxx_messageInfo_StandUpC2S proto.InternalMessageInfo

//--16 玩家离座观战
type StandUpS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,req,name=roomData" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StandUpS2C) Reset()         { *m = StandUpS2C{} }
func (m *StandUpS2C) String() string { return proto.CompactTextString(m) }
func (*StandUpS2C) ProtoMessage()    {}
func (*StandUpS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{22}
}

func (m *StandUpS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandUpS2C.Unmarshal(m, b)
}
func (m *StandUpS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandUpS2C.Marshal(b, m, deterministic)
}
func (m *StandUpS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandUpS2C.Merge(m, src)
}
func (m *StandUpS2C) XXX_Size() int {
	return xxx_messageInfo_StandUpS2C.Size(m)
}
func (m *StandUpS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_StandUpS2C.DiscardUnknown(m)
}

var xxx_messageInfo_StandUpS2C proto.InternalMessageInfo

func (m *StandUpS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

//--17 游戏阶段变更
type GameStepChangeS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,req,name=roomData" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameStepChangeS2C) Reset()         { *m = GameStepChangeS2C{} }
func (m *GameStepChangeS2C) String() string { return proto.CompactTextString(m) }
func (*GameStepChangeS2C) ProtoMessage()    {}
func (*GameStepChangeS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{23}
}

func (m *GameStepChangeS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStepChangeS2C.Unmarshal(m, b)
}
func (m *GameStepChangeS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStepChangeS2C.Marshal(b, m, deterministic)
}
func (m *GameStepChangeS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStepChangeS2C.Merge(m, src)
}
func (m *GameStepChangeS2C) XXX_Size() int {
	return xxx_messageInfo_GameStepChangeS2C.Size(m)
}
func (m *GameStepChangeS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStepChangeS2C.DiscardUnknown(m)
}

var xxx_messageInfo_GameStepChangeS2C proto.InternalMessageInfo

func (m *GameStepChangeS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

//--18 行动的玩家变更
type ActionPlayerChangedS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,req,name=roomData" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActionPlayerChangedS2C) Reset()         { *m = ActionPlayerChangedS2C{} }
func (m *ActionPlayerChangedS2C) String() string { return proto.CompactTextString(m) }
func (*ActionPlayerChangedS2C) ProtoMessage()    {}
func (*ActionPlayerChangedS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{24}
}

func (m *ActionPlayerChangedS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionPlayerChangedS2C.Unmarshal(m, b)
}
func (m *ActionPlayerChangedS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionPlayerChangedS2C.Marshal(b, m, deterministic)
}
func (m *ActionPlayerChangedS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionPlayerChangedS2C.Merge(m, src)
}
func (m *ActionPlayerChangedS2C) XXX_Size() int {
	return xxx_messageInfo_ActionPlayerChangedS2C.Size(m)
}
func (m *ActionPlayerChangedS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionPlayerChangedS2C.DiscardUnknown(m)
}

var xxx_messageInfo_ActionPlayerChangedS2C proto.InternalMessageInfo

func (m *ActionPlayerChangedS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

//--19 玩家行动 命令
type PlayerActionC2S struct {
	BetAmount            *float64            `protobuf:"fixed64,1,opt,name=betAmount" json:"betAmount,omitempty"`
	Action               *Enum_ActionOptions `protobuf:"varint,2,req,name=action,enum=pb_msg.Enum_ActionOptions" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PlayerActionC2S) Reset()         { *m = PlayerActionC2S{} }
func (m *PlayerActionC2S) String() string { return proto.CompactTextString(m) }
func (*PlayerActionC2S) ProtoMessage()    {}
func (*PlayerActionC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{25}
}

func (m *PlayerActionC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerActionC2S.Unmarshal(m, b)
}
func (m *PlayerActionC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerActionC2S.Marshal(b, m, deterministic)
}
func (m *PlayerActionC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerActionC2S.Merge(m, src)
}
func (m *PlayerActionC2S) XXX_Size() int {
	return xxx_messageInfo_PlayerActionC2S.Size(m)
}
func (m *PlayerActionC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerActionC2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerActionC2S proto.InternalMessageInfo

func (m *PlayerActionC2S) GetBetAmount() float64 {
	if m != nil && m.BetAmount != nil {
		return *m.BetAmount
	}
	return 0
}

func (m *PlayerActionC2S) GetAction() Enum_ActionOptions {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return Enum_ActionOptions_ACT_FOLD
}

//--20 玩家行动
type PlayerActionS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,req,name=roomData" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerActionS2C) Reset()         { *m = PlayerActionS2C{} }
func (m *PlayerActionS2C) String() string { return proto.CompactTextString(m) }
func (*PlayerActionS2C) ProtoMessage()    {}
func (*PlayerActionS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{26}
}

func (m *PlayerActionS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerActionS2C.Unmarshal(m, b)
}
func (m *PlayerActionS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerActionS2C.Marshal(b, m, deterministic)
}
func (m *PlayerActionS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerActionS2C.Merge(m, src)
}
func (m *PlayerActionS2C) XXX_Size() int {
	return xxx_messageInfo_PlayerActionS2C.Size(m)
}
func (m *PlayerActionS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerActionS2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerActionS2C proto.InternalMessageInfo

func (m *PlayerActionS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb_msg.Enum_SvrTipType", Enum_SvrTipType_name, Enum_SvrTipType_value)
	proto.RegisterEnum("pb_msg.Enum_CardKind", Enum_CardKind_name, Enum_CardKind_value)
	proto.RegisterEnum("pb_msg.Enum_CardSuit", Enum_CardSuit_name, Enum_CardSuit_value)
	proto.RegisterEnum("pb_msg.Enum_ActionOptions", Enum_ActionOptions_name, Enum_ActionOptions_value)
	proto.RegisterEnum("pb_msg.Enum_Blind", Enum_Blind_name, Enum_Blind_value)
	proto.RegisterEnum("pb_msg.Enum_GameStep", Enum_GameStep_name, Enum_GameStep_value)
	proto.RegisterEnum("pb_msg.Enum_PlayerStatus", Enum_PlayerStatus_name, Enum_PlayerStatus_value)
	proto.RegisterEnum("pb_msg.Enum_ActionTimeS", Enum_ActionTimeS_name, Enum_ActionTimeS_value)
	proto.RegisterType((*PingC2S)(nil), "pb_msg.Ping_c2s")
	proto.RegisterType((*PongS2C)(nil), "pb_msg.Pong_s2c")
	proto.RegisterType((*SvrMsgS2C)(nil), "pb_msg.SvrMsg_s2c")
	proto.RegisterType((*PlayerInfo)(nil), "pb_msg.PlayerInfo")
	proto.RegisterType((*LoginInfo)(nil), "pb_msg.LoginInfo")
	proto.RegisterType((*LoginC2S)(nil), "pb_msg.Login_c2s")
	proto.RegisterType((*LoginResultS2C)(nil), "pb_msg.LoginResult_s2c")
	proto.RegisterType((*CardSuitData)(nil), "pb_msg.CardSuitData")
	proto.RegisterType((*RoomInfo)(nil), "pb_msg.RoomInfo")
	proto.RegisterType((*PlayerData)(nil), "pb_msg.PlayerData")
	proto.RegisterType((*RoomData)(nil), "pb_msg.RoomData")
	proto.RegisterType((*QuickStartC2S)(nil), "pb_msg.QuickStart_c2s")
	proto.RegisterType((*CreateRoomC2S)(nil), "pb_msg.CreateRoom_c2s")
	proto.RegisterType((*JoinRoomC2S)(nil), "pb_msg.JoinRoom_c2s")
	proto.RegisterType((*EnterRoomS2C)(nil), "pb_msg.EnterRoom_s2c")
	proto.RegisterType((*ExitRoomC2S)(nil), "pb_msg.ExitRoom_c2s")
	proto.RegisterType((*ExitRoomS2C)(nil), "pb_msg.ExitRoom_s2c")
	proto.RegisterType((*OtherPlayerJoinS2C)(nil), "pb_msg.OtherPlayerJoin_s2c")
	proto.RegisterType((*OtherPlayerLeaveS2C)(nil), "pb_msg.OtherPlayerLeave_s2c")
	proto.RegisterType((*SitDownC2S)(nil), "pb_msg.SitDown_c2s")
	proto.RegisterType((*SitDownS2C)(nil), "pb_msg.SitDown_s2c")
	proto.RegisterType((*StandUpC2S)(nil), "pb_msg.StandUp_c2s")
	proto.RegisterType((*StandUpS2C)(nil), "pb_msg.StandUp_s2c")
	proto.RegisterType((*GameStepChangeS2C)(nil), "pb_msg.GameStepChange_s2c")
	proto.RegisterType((*ActionPlayerChangedS2C)(nil), "pb_msg.ActionPlayerChanged_s2c")
	proto.RegisterType((*PlayerActionC2S)(nil), "pb_msg.PlayerAction_c2s")
	proto.RegisterType((*PlayerActionS2C)(nil), "pb_msg.PlayerAction_s2c")
}

func init() { proto.RegisterFile("pb_msg.proto", fileDescriptor_bd13c7201b21be60) }

var fileDescriptor_bd13c7201b21be60 = []byte{
	// 1415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xed, 0x8e, 0xda, 0x46,
	0x17, 0x5e, 0xcc, 0x97, 0x39, 0xb0, 0xec, 0x64, 0xb2, 0xef, 0x1b, 0x37, 0x4a, 0x23, 0x64, 0x55,
	0xd5, 0x16, 0x55, 0x89, 0x82, 0x2a, 0x35, 0x6a, 0x92, 0xaa, 0x06, 0x0c, 0xb8, 0xeb, 0xc5, 0x74,
	0x6c, 0xba, 0xe9, 0x9f, 0x5a, 0x5e, 0xec, 0x10, 0xab, 0x60, 0x23, 0xdb, 0x6c, 0xb2, 0xbf, 0x7b,
	0x09, 0xbd, 0x87, 0x5e, 0x45, 0xef, 0xa2, 0x57, 0xd2, 0x3b, 0xa8, 0x66, 0xc6, 0x36, 0x66, 0x83,
	0x2a, 0xed, 0xfe, 0xb1, 0xe6, 0x9c, 0x79, 0xe6, 0x39, 0x9f, 0x73, 0xc6, 0xd0, 0xda, 0x5c, 0xd9,
	0xeb, 0x78, 0xf9, 0x6c, 0x13, 0x85, 0x49, 0x88, 0x6b, 0x5c, 0x92, 0x01, 0xc4, 0x99, 0x1f, 0x2c,
	0xed, 0x45, 0x2f, 0x96, 0xbb, 0x20, 0xce, 0xc2, 0x60, 0x69, 0xc7, 0xbd, 0x05, 0x7e, 0x0a, 0x10,
	0x7b, 0xd1, 0xb5, 0x17, 0x59, 0xfe, 0xda, 0x93, 0x4a, 0x1d, 0xe1, 0xac, 0x4c, 0x0a, 0x1a, 0x79,
	0x09, 0x60, 0x5e, 0x47, 0x17, 0x31, 0x47, 0x63, 0xa8, 0x2c, 0x42, 0x97, 0xe3, 0xaa, 0x84, 0xad,
	0xa9, 0xce, 0x75, 0x12, 0x47, 0x12, 0x3a, 0xc2, 0x59, 0x83, 0xb0, 0x35, 0x7e, 0x01, 0xf5, 0xc4,
	0xdf, 0x58, 0x37, 0x1b, 0x4f, 0x2a, 0x77, 0x84, 0xb3, 0x76, 0xef, 0xd1, 0xb3, 0xd4, 0x2b, 0x35,
	0xd8, 0xae, 0x6d, 0xf3, 0x3a, 0xb2, 0xf8, 0x36, 0xc9, 0x70, 0xf2, 0xaf, 0x00, 0xb3, 0x95, 0x73,
	0xe3, 0x45, 0x5a, 0xf0, 0x2e, 0xc4, 0x6d, 0x10, 0x7c, 0x97, 0x99, 0x69, 0x10, 0xc1, 0x77, 0xa9,
	0x91, 0xc0, 0x59, 0x7b, 0x99, 0x11, 0xba, 0xa6, 0xba, 0x77, 0xce, 0x82, 0x5b, 0x68, 0x10, 0xb6,
	0xc6, 0x12, 0xd4, 0xaf, 0x9c, 0x95, 0x13, 0x2c, 0x3c, 0xa9, 0xd2, 0x11, 0xce, 0x4a, 0x24, 0x13,
	0x65, 0x13, 0x1a, 0x7a, 0xb8, 0xf4, 0x83, 0x83, 0xf4, 0x8f, 0xa0, 0xbe, 0x74, 0xd6, 0x9e, 0xed,
	0xbb, 0xa9, 0x85, 0x1a, 0x15, 0x35, 0x17, 0x7f, 0x9e, 0xa5, 0xc7, 0xde, 0x46, 0xab, 0xd4, 0x52,
	0x83, 0x6b, 0xe6, 0xd1, 0x4a, 0x7e, 0x9d, 0x92, 0xd2, 0xb4, 0xe2, 0xe7, 0xd0, 0x58, 0x65, 0x16,
	0x18, 0x77, 0xb3, 0xf7, 0x20, 0x0b, 0x3b, 0x37, 0x4d, 0x76, 0x18, 0x59, 0x85, 0x13, 0xa6, 0x27,
	0x5e, 0xbc, 0x5d, 0x25, 0x2c, 0xc1, 0x3d, 0x80, 0x4d, 0x9e, 0x85, 0x94, 0x04, 0x67, 0x24, 0xbb,
	0xfc, 0x90, 0x02, 0x4a, 0xfe, 0xa3, 0x04, 0xad, 0x81, 0x13, 0xb9, 0xe6, 0xd6, 0x4f, 0x86, 0x34,
	0xfb, 0x32, 0xb4, 0xde, 0x3b, 0x81, 0x4b, 0x75, 0xe7, 0xde, 0x4d, 0x2c, 0x95, 0x3a, 0xe5, 0xb3,
	0x2a, 0xd9, 0xd3, 0xe1, 0x2f, 0xa1, 0xbd, 0xd9, 0x5e, 0xad, 0xfc, 0x45, 0x8e, 0x12, 0x18, 0xea,
	0x96, 0x16, 0x7f, 0x0b, 0xcd, 0x78, 0xeb, 0x27, 0x33, 0x27, 0x49, 0xbc, 0x28, 0x48, 0xab, 0xf9,
	0xbf, 0xbd, 0x6a, 0x66, 0xb6, 0x49, 0x11, 0x29, 0xff, 0x59, 0x02, 0x91, 0x84, 0xe1, 0x9a, 0xe5,
	0xfb, 0xff, 0x50, 0x8b, 0xe8, 0x9a, 0xe6, 0xbc, 0x44, 0xd3, 0xcb, 0x25, 0x7c, 0x0a, 0xd5, 0xc5,
	0xbb, 0xa5, 0x96, 0x65, 0x9d, 0x0b, 0xf8, 0x09, 0x34, 0xd6, 0xce, 0x47, 0x1e, 0x2d, 0xb3, 0x58,
	0x25, 0x3b, 0x05, 0x7e, 0x0d, 0x2d, 0x67, 0x91, 0xf8, 0x61, 0x40, 0xfb, 0xd3, 0x8e, 0x59, 0x9d,
	0xdb, 0xbd, 0xcf, 0xf6, 0x5c, 0x52, 0x0a, 0x00, 0xd2, 0xdc, 0xc1, 0x4d, 0x8c, 0xa0, 0xbc, 0xf9,
	0xe0, 0x4a, 0x55, 0xe6, 0x06, 0x5d, 0xca, 0xff, 0x94, 0xb3, 0xce, 0x63, 0xc9, 0xbb, 0x47, 0x05,
	0xf0, 0x63, 0x10, 0x37, 0x61, 0xec, 0x53, 0x2b, 0x2c, 0x92, 0x2a, 0xc9, 0x65, 0xba, 0xe7, 0xc7,
	0xc4, 0xf1, 0x63, 0xcf, 0x65, 0xb1, 0x88, 0x24, 0x97, 0xf1, 0x1b, 0x68, 0x71, 0x16, 0x33, 0x71,
	0x92, 0xed, 0xe1, 0x50, 0x66, 0x05, 0x00, 0xd9, 0x83, 0xd3, 0xbb, 0xeb, 0x46, 0xe1, 0xc6, 0x73,
	0xfb, 0x5e, 0x12, 0x4b, 0x55, 0xd6, 0xef, 0x05, 0x0d, 0xfe, 0x02, 0x8e, 0x77, 0x92, 0xb9, 0x5d,
	0x4b, 0x35, 0x06, 0xd9, 0x57, 0x52, 0x07, 0x17, 0x59, 0x0f, 0xd4, 0x59, 0x0f, 0xe4, 0x32, 0x7e,
	0x09, 0xad, 0x45, 0xa1, 0xb3, 0x24, 0x91, 0xa5, 0xe3, 0x34, 0x73, 0xb0, 0xd8, 0x75, 0x64, 0x0f,
	0xc9, 0xc3, 0xbe, 0xf4, 0x83, 0xc0, 0x8b, 0xa4, 0x46, 0x16, 0x36, 0x97, 0xf1, 0x19, 0x54, 0xaf,
	0x56, 0x7e, 0xe0, 0x4a, 0xc0, 0xe2, 0xc5, 0x7b, 0xf1, 0xf6, 0xe9, 0x0e, 0xe1, 0x00, 0xce, 0xd2,
	0xdf, 0x26, 0x49, 0x18, 0x48, 0xcd, 0x8c, 0x85, 0xcb, 0xf4, 0xaa, 0xfb, 0xb1, 0xb2, 0x5a, 0x69,
	0x81, 0xd4, 0x62, 0x5b, 0x99, 0x88, 0x3b, 0xd0, 0x8c, 0xd8, 0x95, 0xba, 0x08, 0x03, 0xef, 0x46,
	0x3a, 0x66, 0x51, 0x17, 0x55, 0xf2, 0xdf, 0x02, 0x6f, 0x4e, 0xe6, 0xea, 0xd7, 0x20, 0x46, 0x69,
	0xa3, 0xa6, 0xf5, 0x46, 0x99, 0x47, 0x59, 0x03, 0x93, 0x1c, 0x41, 0x9b, 0xd3, 0x8f, 0xcd, 0xc4,
	0xdb, 0xa8, 0x01, 0x6f, 0x5b, 0x91, 0xec, 0x14, 0xf8, 0x05, 0x88, 0x74, 0x72, 0x50, 0xf1, 0xe0,
	0x5d, 0x19, 0xa7, 0x9b, 0x24, 0x87, 0xd1, 0x18, 0xd7, 0x7e, 0xc0, 0x3a, 0x22, 0x9d, 0x59, 0xb9,
	0x4c, 0x8d, 0xd1, 0xe6, 0xbd, 0xf6, 0x66, 0x21, 0x2f, 0x70, 0x95, 0xec, 0x14, 0xb4, 0xfe, 0x81,
	0xf7, 0x31, 0xa1, 0x2c, 0x56, 0xcc, 0x8a, 0x5b, 0x26, 0x05, 0x0d, 0xeb, 0xf5, 0x30, 0x91, 0xea,
	0x8c, 0x94, 0x2e, 0x0f, 0xdc, 0x7a, 0xf1, 0xe0, 0xad, 0xff, 0x06, 0x9a, 0x9b, 0xfc, 0x4a, 0xc4,
	0x52, 0xa3, 0x53, 0xfe, 0xf4, 0x16, 0xb0, 0xa2, 0x17, 0x61, 0xf2, 0xf7, 0xd0, 0xfe, 0x69, 0xeb,
	0x2f, 0x7e, 0x33, 0x13, 0x27, 0x4a, 0xd8, 0x48, 0xbc, 0x53, 0x6a, 0xe9, 0xf9, 0x41, 0xe4, 0x39,
	0x89, 0x47, 0xf7, 0xee, 0x71, 0xfe, 0x25, 0xb4, 0x7e, 0x0c, 0xfd, 0x20, 0x3f, 0x5d, 0x9c, 0x3a,
	0x42, 0x61, 0xea, 0xa4, 0x33, 0x80, 0xcf, 0x1c, 0x36, 0x03, 0xde, 0xc0, 0xb1, 0x1a, 0x24, 0x5e,
	0xc4, 0x8e, 0xd2, 0x39, 0x9c, 0x1a, 0x66, 0x4d, 0x7f, 0xc0, 0x30, 0x8b, 0x3d, 0x47, 0xc8, 0x4f,
	0xa1, 0xa5, 0x7e, 0xf4, 0x93, 0xdc, 0x70, 0x1b, 0x84, 0xdc, 0xa8, 0xa0, 0xb9, 0x72, 0xbf, 0xb0,
	0x7f, 0xdf, 0x29, 0xaf, 0xc1, 0x43, 0x23, 0x79, 0xef, 0x45, 0x7c, 0x9b, 0xc6, 0xb9, 0x4f, 0x55,
	0x70, 0xf5, 0x50, 0xa1, 0x0a, 0x28, 0x79, 0x08, 0xa7, 0x05, 0x2a, 0xdd, 0x73, 0xae, 0x3d, 0xc6,
	0x55, 0x1c, 0x63, 0xa5, 0x5b, 0x63, 0x2c, 0xed, 0x25, 0x21, 0xef, 0x25, 0xf9, 0x2b, 0x68, 0x9a,
	0x7e, 0x32, 0x0c, 0x3f, 0xf0, 0xd7, 0xef, 0x3f, 0x0e, 0xcb, 0xaf, 0x76, 0xd0, 0xbb, 0x27, 0xf7,
	0x18, 0x9a, 0x66, 0xe2, 0x04, 0xee, 0x7c, 0xc3, 0x7e, 0x5e, 0x5e, 0xed, 0xc4, 0xbb, 0x73, 0xf5,
	0x01, 0x67, 0x37, 0x70, 0xf0, 0xde, 0x09, 0x96, 0xde, 0x3d, 0x38, 0xc6, 0xf0, 0x88, 0x3f, 0x2f,
	0x3c, 0x7d, 0x9c, 0xc7, 0xbd, 0x07, 0x91, 0x0b, 0x88, 0x53, 0x70, 0x3a, 0x96, 0xc5, 0x27, 0xd0,
	0xb8, 0xf2, 0x12, 0x65, 0x1d, 0x6e, 0x83, 0x84, 0xbd, 0x95, 0x25, 0xb2, 0x53, 0xe0, 0x1e, 0xd4,
	0xf8, 0x5b, 0xc6, 0xea, 0xd0, 0xee, 0x3d, 0x3e, 0xf0, 0xe8, 0x19, 0x1b, 0xfa, 0x8d, 0x49, 0x8a,
	0x94, 0x7f, 0xb8, 0x65, 0xe5, 0xce, 0x7e, 0x76, 0x9f, 0xc3, 0xc9, 0xad, 0xbf, 0x36, 0x5c, 0x87,
	0xf2, 0x85, 0x39, 0x46, 0x47, 0x58, 0x84, 0xca, 0xa5, 0x42, 0xa6, 0xa8, 0x84, 0x1b, 0x50, 0x55,
	0x09, 0x31, 0x08, 0x12, 0xba, 0x63, 0x7a, 0x9b, 0xd2, 0x1f, 0x83, 0x73, 0x3a, 0xc6, 0x45, 0xa8,
	0x4c, 0x8d, 0xa9, 0x8a, 0x8e, 0x70, 0x13, 0xea, 0x43, 0x4d, 0xb9, 0x30, 0xa6, 0x43, 0x7e, 0x64,
	0xa0, 0xcf, 0xfb, 0x26, 0x12, 0xe8, 0x72, 0xa2, 0x2a, 0xc4, 0x42, 0x65, 0xba, 0x34, 0x67, 0xca,
	0x50, 0x45, 0x95, 0xee, 0x5f, 0xa5, 0x02, 0x13, 0x7d, 0x5a, 0x18, 0xd3, 0x5c, 0xd7, 0xd1, 0x11,
	0x3e, 0x86, 0xc6, 0x44, 0x1b, 0x4f, 0xec, 0x81, 0x42, 0x28, 0x57, 0x0b, 0x44, 0x63, 0xaa, 0xda,
	0x33, 0x45, 0x23, 0x48, 0xa0, 0x9b, 0xd6, 0xa5, 0xc1, 0x24, 0x13, 0x95, 0xf1, 0x43, 0x38, 0xb1,
	0x26, 0x44, 0x55, 0x6d, 0x63, 0x64, 0x2b, 0xf6, 0xb9, 0x36, 0x1d, 0xa2, 0x0a, 0x3d, 0x61, 0x5a,
	0x44, 0xd1, 0xc6, 0x13, 0x0b, 0x55, 0xa9, 0xd5, 0x91, 0x3e, 0x37, 0x27, 0xa8, 0x86, 0xdb, 0x00,
	0xa3, 0xb9, 0xae, 0xdb, 0x13, 0x63, 0x6e, 0xaa, 0xa8, 0x8e, 0x31, 0xb4, 0x47, 0xc6, 0x9c, 0x14,
	0x0e, 0x8b, 0x54, 0x97, 0x1d, 0xb6, 0xf9, 0xb9, 0x06, 0x3e, 0x81, 0x26, 0x31, 0x7e, 0x51, 0xf4,
	0x54, 0x01, 0xdd, 0x29, 0xe0, 0x4f, 0x0b, 0x43, 0xed, 0x2a, 0x03, 0xcb, 0x1e, 0x19, 0xfa, 0x10,
	0x1d, 0x65, 0xd2, 0x40, 0xd1, 0x75, 0x54, 0xa2, 0x7e, 0x53, 0x89, 0x28, 0x9a, 0xa9, 0xf2, 0x30,
	0xd8, 0xe6, 0x44, 0x1d, 0x9c, 0xa3, 0x72, 0xf7, 0x3b, 0x80, 0xdd, 0x13, 0x49, 0x4f, 0x4e, 0x0d,
	0xbb, 0xaf, 0x53, 0x87, 0x8e, 0xa8, 0x71, 0xf3, 0x42, 0xd1, 0xf5, 0x54, 0xc1, 0xa8, 0xfa, 0xda,
	0x38, 0x15, 0x85, 0xee, 0x75, 0x9a, 0xc9, 0xac, 0xfd, 0x31, 0x82, 0x96, 0x69, 0xa9, 0x33, 0xfb,
	0x52, 0xd1, 0x2c, 0x6d, 0x4a, 0x6b, 0xf9, 0x00, 0x8e, 0x99, 0x66, 0x46, 0x54, 0x7b, 0xa4, 0x1b,
	0x33, 0x4e, 0xc2, 0x54, 0x4c, 0x14, 0x72, 0xd1, 0x9a, 0x93, 0x29, 0x2a, 0xd3, 0x44, 0x31, 0x91,
	0x68, 0x3f, 0xab, 0x04, 0x55, 0x78, 0x52, 0xd4, 0x99, 0x6d, 0x4e, 0x8c, 0x4b, 0x7b, 0x68, 0x5c,
	0x4e, 0x51, 0xb5, 0xfb, 0x7b, 0x09, 0x1e, 0x7c, 0xf2, 0x1f, 0xc3, 0x91, 0x8a, 0x35, 0x37, 0x0b,
	0xe6, 0x99, 0x43, 0x4c, 0xc7, 0xc3, 0x2f, 0xb1, 0x98, 0xb8, 0x86, 0xa5, 0x47, 0x28, 0x40, 0xd2,
	0x94, 0x14, 0x20, 0x2c, 0x9f, 0x15, 0x7c, 0x0a, 0x28, 0x55, 0x14, 0xbd, 0xe8, 0xa5, 0x4e, 0x14,
	0xff, 0x0b, 0x69, 0x13, 0xbf, 0x7d, 0xfb, 0x16, 0x1d, 0x61, 0x80, 0xda, 0xd4, 0x20, 0x17, 0x8a,
	0x8e, 0x4e, 0x68, 0x83, 0x8d, 0x14, 0xd3, 0x42, 0xf0, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95,
	0x6d, 0x62, 0xca, 0x48, 0x0d, 0x00, 0x00,
}
