// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_msg.proto

package pb_msg

import (
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enum_SvrTipType int32

const (
	Enum_SvrTipType_MSG   Enum_SvrTipType = 0
	Enum_SvrTipType_WARN  Enum_SvrTipType = 1
	Enum_SvrTipType_ERROR Enum_SvrTipType = 2
)

var Enum_SvrTipType_name = map[int32]string{
	0: "MSG",
	1: "WARN",
	2: "ERROR",
}

var Enum_SvrTipType_value = map[string]int32{
	"MSG":   0,
	"WARN":  1,
	"ERROR": 2,
}

func (x Enum_SvrTipType) String() string {
	return proto.EnumName(Enum_SvrTipType_name, int32(x))
}

func (Enum_SvrTipType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{0}
}

// 牌花色
type Enum_CardKind int32

const (
	Enum_CardKind_NONE    Enum_CardKind = 0
	Enum_CardKind_DIAMOND Enum_CardKind = 1
	Enum_CardKind_CLUBS   Enum_CardKind = 2
	Enum_CardKind_HEART   Enum_CardKind = 3
	Enum_CardKind_SPADE   Enum_CardKind = 4
)

var Enum_CardKind_name = map[int32]string{
	0: "NONE",
	1: "DIAMOND",
	2: "CLUBS",
	3: "HEART",
	4: "SPADE",
}

var Enum_CardKind_value = map[string]int32{
	"NONE":    0,
	"DIAMOND": 1,
	"CLUBS":   2,
	"HEART":   3,
	"SPADE":   4,
}

func (x Enum_CardKind) String() string {
	return proto.EnumName(Enum_CardKind_name, int32(x))
}

func (Enum_CardKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{1}
}

// 牌型
type Enum_CardSuit int32

const (
	Enum_CardSuit_NULL Enum_CardSuit = 0
	// 高牌
	Enum_CardSuit_HIGH_CARD Enum_CardSuit = 1
	// 一对
	Enum_CardSuit_ONE_PAIR Enum_CardSuit = 2
	// 两对
	Enum_CardSuit_TWO_PAIRS Enum_CardSuit = 3
	// 三条
	Enum_CardSuit_THREE_OF_A_KIND Enum_CardSuit = 4
	// 顺子
	Enum_CardSuit_STRAIGHT Enum_CardSuit = 5
	// 同花
	Enum_CardSuit_FLUSH Enum_CardSuit = 6
	// 葫芦
	Enum_CardSuit_FULL_HOUSE Enum_CardSuit = 7
	// 四条
	Enum_CardSuit_FOUR_OF_A_KIND Enum_CardSuit = 8
	// 同花顺
	Enum_CardSuit_STRAIGHT_FLUSH Enum_CardSuit = 9
	// 皇家同花顺
	Enum_CardSuit_ROYAL_FLUSH Enum_CardSuit = 10
)

var Enum_CardSuit_name = map[int32]string{
	0:  "NULL",
	1:  "HIGH_CARD",
	2:  "ONE_PAIR",
	3:  "TWO_PAIRS",
	4:  "THREE_OF_A_KIND",
	5:  "STRAIGHT",
	6:  "FLUSH",
	7:  "FULL_HOUSE",
	8:  "FOUR_OF_A_KIND",
	9:  "STRAIGHT_FLUSH",
	10: "ROYAL_FLUSH",
}

var Enum_CardSuit_value = map[string]int32{
	"NULL":            0,
	"HIGH_CARD":       1,
	"ONE_PAIR":        2,
	"TWO_PAIRS":       3,
	"THREE_OF_A_KIND": 4,
	"STRAIGHT":        5,
	"FLUSH":           6,
	"FULL_HOUSE":      7,
	"FOUR_OF_A_KIND":  8,
	"STRAIGHT_FLUSH":  9,
	"ROYAL_FLUSH":     10,
}

func (x Enum_CardSuit) String() string {
	return proto.EnumName(Enum_CardSuit_name, int32(x))
}

func (Enum_CardSuit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{2}
}

// 玩家操作类型
type Enum_ActionOptions int32

const (
	Enum_ActionOptions_ACT_JOIN_ROOM  Enum_ActionOptions = 0
	Enum_ActionOptions_ACT_SIT        Enum_ActionOptions = 1
	Enum_ActionOptions_ACT_STAND_UP   Enum_ActionOptions = 2
	Enum_ActionOptions_ACT_LEAVE_ROOM Enum_ActionOptions = 3
	Enum_ActionOptions_ACT_FOLD       Enum_ActionOptions = 4
	Enum_ActionOptions_ACT_CALL       Enum_ActionOptions = 5
	Enum_ActionOptions_ACT_RAISE      Enum_ActionOptions = 6
	Enum_ActionOptions_ACT_CHECK      Enum_ActionOptions = 7
)

var Enum_ActionOptions_name = map[int32]string{
	0: "ACT_JOIN_ROOM",
	1: "ACT_SIT",
	2: "ACT_STAND_UP",
	3: "ACT_LEAVE_ROOM",
	4: "ACT_FOLD",
	5: "ACT_CALL",
	6: "ACT_RAISE",
	7: "ACT_CHECK",
}

var Enum_ActionOptions_value = map[string]int32{
	"ACT_JOIN_ROOM":  0,
	"ACT_SIT":        1,
	"ACT_STAND_UP":   2,
	"ACT_LEAVE_ROOM": 3,
	"ACT_FOLD":       4,
	"ACT_CALL":       5,
	"ACT_RAISE":      6,
	"ACT_CHECK":      7,
}

func (x Enum_ActionOptions) String() string {
	return proto.EnumName(Enum_ActionOptions_name, int32(x))
}

func (Enum_ActionOptions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{3}
}

// 盲注类型
type Enum_Blind int32

const (
	Enum_Blind_NO_BLIND    Enum_Blind = 0
	Enum_Blind_SMALL_BLIND Enum_Blind = 1
	Enum_Blind_BIG_BLIND   Enum_Blind = 2
)

var Enum_Blind_name = map[int32]string{
	0: "NO_BLIND",
	1: "SMALL_BLIND",
	2: "BIG_BLIND",
}

var Enum_Blind_value = map[string]int32{
	"NO_BLIND":    0,
	"SMALL_BLIND": 1,
	"BIG_BLIND":   2,
}

func (x Enum_Blind) String() string {
	return proto.EnumName(Enum_Blind_name, int32(x))
}

func (Enum_Blind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{4}
}

// 游戏阶段
type Enum_GameStep int32

const (
	Enum_GameStep_STEP_WAITING   Enum_GameStep = 0
	Enum_GameStep_STEP_PRE_FLOP  Enum_GameStep = 1
	Enum_GameStep_STEP_FLOP      Enum_GameStep = 2
	Enum_GameStep_STEP_TURN      Enum_GameStep = 3
	Enum_GameStep_STEP_RIVER     Enum_GameStep = 4
	Enum_GameStep_STEP_SHOW_DOWN Enum_GameStep = 5
)

var Enum_GameStep_name = map[int32]string{
	0: "STEP_WAITING",
	1: "STEP_PRE_FLOP",
	2: "STEP_FLOP",
	3: "STEP_TURN",
	4: "STEP_RIVER",
	5: "STEP_SHOW_DOWN",
}

var Enum_GameStep_value = map[string]int32{
	"STEP_WAITING":   0,
	"STEP_PRE_FLOP":  1,
	"STEP_FLOP":      2,
	"STEP_TURN":      3,
	"STEP_RIVER":     4,
	"STEP_SHOW_DOWN": 5,
}

func (x Enum_GameStep) String() string {
	return proto.EnumName(Enum_GameStep_name, int32(x))
}

func (Enum_GameStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{5}
}

// 本轮玩家表态
type Enum_PlayerStatus int32

const (
	Enum_PlayerStatus_STATUS_WAITING   Enum_PlayerStatus = 0 // 尚未表态
	Enum_PlayerStatus_STATUS_RAISE     Enum_PlayerStatus = 1 // 加注
	Enum_PlayerStatus_STATUS_CALL      Enum_PlayerStatus = 2 // 跟牌
	Enum_PlayerStatus_STATUS_CHECK     Enum_PlayerStatus = 3 // 过牌
	Enum_PlayerStatus_STATUS_FOLD      Enum_PlayerStatus = 4 // 弃牌
	Enum_PlayerStatus_STATUS_SHOW_DOWN Enum_PlayerStatus = 5 // 摊牌
)

var Enum_PlayerStatus_name = map[int32]string{
	0: "STATUS_WAITING",
	1: "STATUS_RAISE",
	2: "STATUS_CALL",
	3: "STATUS_CHECK",
	4: "STATUS_FOLD",
	5: "STATUS_SHOW_DOWN",
}

var Enum_PlayerStatus_value = map[string]int32{
	"STATUS_WAITING":   0,
	"STATUS_RAISE":     1,
	"STATUS_CALL":      2,
	"STATUS_CHECK":     3,
	"STATUS_FOLD":      4,
	"STATUS_SHOW_DOWN": 5,
}

func (x Enum_PlayerStatus) String() string {
	return proto.EnumName(Enum_PlayerStatus_name, int32(x))
}

func (Enum_PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{6}
}

// 游戏中每个玩家行动时间
type Enum_ActionTimeS int32

const (
	Enum_ActionTimeS_XXX    Enum_ActionTimeS = 0
	Enum_ActionTimeS_NORMAL Enum_ActionTimeS = 15
	Enum_ActionTimeS_FAST   Enum_ActionTimeS = 10
)

var Enum_ActionTimeS_name = map[int32]string{
	0:  "XXX",
	15: "NORMAL",
	10: "FAST",
}

var Enum_ActionTimeS_value = map[string]int32{
	"XXX":    0,
	"NORMAL": 15,
	"FAST":   10,
}

func (x Enum_ActionTimeS) String() string {
	return proto.EnumName(Enum_ActionTimeS_name, int32(x))
}

func (Enum_ActionTimeS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{7}
}

//--0
type PingC2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingC2S) Reset()         { *m = PingC2S{} }
func (m *PingC2S) String() string { return proto.CompactTextString(m) }
func (*PingC2S) ProtoMessage()    {}
func (*PingC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{0}
}

func (m *PingC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingC2S.Unmarshal(m, b)
}
func (m *PingC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingC2S.Marshal(b, m, deterministic)
}
func (m *PingC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingC2S.Merge(m, src)
}
func (m *PingC2S) XXX_Size() int {
	return xxx_messageInfo_PingC2S.Size(m)
}
func (m *PingC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PingC2S.DiscardUnknown(m)
}

var xxx_messageInfo_PingC2S proto.InternalMessageInfo

//--1
type PongS2C struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongS2C) Reset()         { *m = PongS2C{} }
func (m *PongS2C) String() string { return proto.CompactTextString(m) }
func (*PongS2C) ProtoMessage()    {}
func (*PongS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{1}
}

func (m *PongS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongS2C.Unmarshal(m, b)
}
func (m *PongS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongS2C.Marshal(b, m, deterministic)
}
func (m *PongS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongS2C.Merge(m, src)
}
func (m *PongS2C) XXX_Size() int {
	return xxx_messageInfo_PongS2C.Size(m)
}
func (m *PongS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PongS2C.DiscardUnknown(m)
}

var xxx_messageInfo_PongS2C proto.InternalMessageInfo

func (m *PongS2C) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

//--2
type SvrMsgS2C struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TipType              Enum_SvrTipType `protobuf:"varint,3,opt,name=tipType,proto3,enum=pb_msg.Enum_SvrTipType" json:"tipType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SvrMsgS2C) Reset()         { *m = SvrMsgS2C{} }
func (m *SvrMsgS2C) String() string { return proto.CompactTextString(m) }
func (*SvrMsgS2C) ProtoMessage()    {}
func (*SvrMsgS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{2}
}

func (m *SvrMsgS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvrMsgS2C.Unmarshal(m, b)
}
func (m *SvrMsgS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvrMsgS2C.Marshal(b, m, deterministic)
}
func (m *SvrMsgS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvrMsgS2C.Merge(m, src)
}
func (m *SvrMsgS2C) XXX_Size() int {
	return xxx_messageInfo_SvrMsgS2C.Size(m)
}
func (m *SvrMsgS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SvrMsgS2C.DiscardUnknown(m)
}

var xxx_messageInfo_SvrMsgS2C proto.InternalMessageInfo

func (m *SvrMsgS2C) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SvrMsgS2C) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SvrMsgS2C) GetTipType() Enum_SvrTipType {
	if m != nil {
		return m.TipType
	}
	return Enum_SvrTipType_MSG
}

// 玩家基础信息
type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{3}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *PlayerInfo) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// 登录信息
type LoginInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId               string   `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ServerUrl            string   `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{4}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LoginInfo) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *LoginInfo) GetServerUrl() string {
	if m != nil {
		return m.ServerUrl
	}
	return ""
}

//--3
type LoginC2S struct {
	LoginInfo            *LoginInfo `protobuf:"bytes,1,opt,name=loginInfo,proto3" json:"loginInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginC2S) Reset()         { *m = LoginC2S{} }
func (m *LoginC2S) String() string { return proto.CompactTextString(m) }
func (*LoginC2S) ProtoMessage()    {}
func (*LoginC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{5}
}

func (m *LoginC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginC2S.Unmarshal(m, b)
}
func (m *LoginC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginC2S.Marshal(b, m, deterministic)
}
func (m *LoginC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginC2S.Merge(m, src)
}
func (m *LoginC2S) XXX_Size() int {
	return xxx_messageInfo_LoginC2S.Size(m)
}
func (m *LoginC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginC2S.DiscardUnknown(m)
}

var xxx_messageInfo_LoginC2S proto.InternalMessageInfo

func (m *LoginC2S) GetLoginInfo() *LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

//--4
type LoginResultS2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResultS2C) Reset()         { *m = LoginResultS2C{} }
func (m *LoginResultS2C) String() string { return proto.CompactTextString(m) }
func (*LoginResultS2C) ProtoMessage()    {}
func (*LoginResultS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{6}
}

func (m *LoginResultS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResultS2C.Unmarshal(m, b)
}
func (m *LoginResultS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResultS2C.Marshal(b, m, deterministic)
}
func (m *LoginResultS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResultS2C.Merge(m, src)
}
func (m *LoginResultS2C) XXX_Size() int {
	return xxx_messageInfo_LoginResultS2C.Size(m)
}
func (m *LoginResultS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResultS2C.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResultS2C proto.InternalMessageInfo

func (m *LoginResultS2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// 牌型数据
type CardSuitData struct {
	HandCardKeys         []int32       `protobuf:"varint,1,rep,packed,name=handCardKeys,proto3" json:"handCardKeys,omitempty"`
	PublicCardKeys       []int32       `protobuf:"varint,2,rep,packed,name=publicCardKeys,proto3" json:"publicCardKeys,omitempty"`
	SuitPattern          Enum_CardSuit `protobuf:"varint,3,opt,name=suitPattern,proto3,enum=pb_msg.Enum_CardSuit" json:"suitPattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CardSuitData) Reset()         { *m = CardSuitData{} }
func (m *CardSuitData) String() string { return proto.CompactTextString(m) }
func (*CardSuitData) ProtoMessage()    {}
func (*CardSuitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{7}
}

func (m *CardSuitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardSuitData.Unmarshal(m, b)
}
func (m *CardSuitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardSuitData.Marshal(b, m, deterministic)
}
func (m *CardSuitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardSuitData.Merge(m, src)
}
func (m *CardSuitData) XXX_Size() int {
	return xxx_messageInfo_CardSuitData.Size(m)
}
func (m *CardSuitData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardSuitData.DiscardUnknown(m)
}

var xxx_messageInfo_CardSuitData proto.InternalMessageInfo

func (m *CardSuitData) GetHandCardKeys() []int32 {
	if m != nil {
		return m.HandCardKeys
	}
	return nil
}

func (m *CardSuitData) GetPublicCardKeys() []int32 {
	if m != nil {
		return m.PublicCardKeys
	}
	return nil
}

func (m *CardSuitData) GetSuitPattern() Enum_CardSuit {
	if m != nil {
		return m.SuitPattern
	}
	return Enum_CardSuit_NULL
}

// 房间基础信息
type RoomInfo struct {
	RoomId               string           `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CfgId                string           `protobuf:"bytes,2,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	MaxPlayer            int32            `protobuf:"varint,3,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	ActionTimeS          Enum_ActionTimeS `protobuf:"varint,4,opt,name=actionTime_s,json=actionTimeS,proto3,enum=pb_msg.Enum_ActionTimeS" json:"actionTime_s,omitempty"`
	Pwd                  string           `protobuf:"bytes,5,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{8}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomInfo) GetCfgId() string {
	if m != nil {
		return m.CfgId
	}
	return ""
}

func (m *RoomInfo) GetMaxPlayer() int32 {
	if m != nil {
		return m.MaxPlayer
	}
	return 0
}

func (m *RoomInfo) GetActionTimeS() Enum_ActionTimeS {
	if m != nil {
		return m.ActionTimeS
	}
	return Enum_ActionTimeS_XXX
}

func (m *RoomInfo) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

// 玩家数据
type PlayerData struct {
	PlayerInfo           *PlayerInfo       `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	Position             int32             `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	IsRaised             bool              `protobuf:"varint,3,opt,name=isRaised,proto3" json:"isRaised,omitempty"`
	PlayerStatus         Enum_PlayerStatus `protobuf:"varint,4,opt,name=playerStatus,proto3,enum=pb_msg.Enum_PlayerStatus" json:"playerStatus,omitempty"`
	DropedBets           float64           `protobuf:"fixed64,5,opt,name=dropedBets,proto3" json:"dropedBets,omitempty"`
	DropedBetsSum        float64           `protobuf:"fixed64,6,opt,name=dropedBetsSum,proto3" json:"dropedBetsSum,omitempty"`
	CardKeys             []int32           `protobuf:"varint,7,rep,packed,name=cardKeys,proto3" json:"cardKeys,omitempty"`
	CardSuitData         *CardSuitData     `protobuf:"bytes,8,opt,name=cardSuitData,proto3" json:"cardSuitData,omitempty"`
	IsWinner             bool              `protobuf:"varint,9,opt,name=isWinner,proto3" json:"isWinner,omitempty"`
	Blind                Enum_Blind        `protobuf:"varint,10,opt,name=blind,proto3,enum=pb_msg.Enum_Blind" json:"blind,omitempty"`
	IsButton             bool              `protobuf:"varint,11,opt,name=isButton,proto3" json:"isButton,omitempty"`
	IsAllIn              bool              `protobuf:"varint,12,opt,name=isAllIn,proto3" json:"isAllIn,omitempty"`
	IsSelf               bool              `protobuf:"varint,13,opt,name=isSelf,proto3" json:"isSelf,omitempty"`
	ResultMoney          float64           `protobuf:"fixed64,14,opt,name=resultMoney,proto3" json:"resultMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{9}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *PlayerData) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *PlayerData) GetIsRaised() bool {
	if m != nil {
		return m.IsRaised
	}
	return false
}

func (m *PlayerData) GetPlayerStatus() Enum_PlayerStatus {
	if m != nil {
		return m.PlayerStatus
	}
	return Enum_PlayerStatus_STATUS_WAITING
}

func (m *PlayerData) GetDropedBets() float64 {
	if m != nil {
		return m.DropedBets
	}
	return 0
}

func (m *PlayerData) GetDropedBetsSum() float64 {
	if m != nil {
		return m.DropedBetsSum
	}
	return 0
}

func (m *PlayerData) GetCardKeys() []int32 {
	if m != nil {
		return m.CardKeys
	}
	return nil
}

func (m *PlayerData) GetCardSuitData() *CardSuitData {
	if m != nil {
		return m.CardSuitData
	}
	return nil
}

func (m *PlayerData) GetIsWinner() bool {
	if m != nil {
		return m.IsWinner
	}
	return false
}

func (m *PlayerData) GetBlind() Enum_Blind {
	if m != nil {
		return m.Blind
	}
	return Enum_Blind_NO_BLIND
}

func (m *PlayerData) GetIsButton() bool {
	if m != nil {
		return m.IsButton
	}
	return false
}

func (m *PlayerData) GetIsAllIn() bool {
	if m != nil {
		return m.IsAllIn
	}
	return false
}

func (m *PlayerData) GetIsSelf() bool {
	if m != nil {
		return m.IsSelf
	}
	return false
}

func (m *PlayerData) GetResultMoney() float64 {
	if m != nil {
		return m.ResultMoney
	}
	return 0
}

// 房间数据
type RoomData struct {
	RoomInfo             *RoomInfo     `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo,omitempty"`
	IsStepEnd            bool          `protobuf:"varint,2,opt,name=isStepEnd,proto3" json:"isStepEnd,omitempty"`
	GameStep             Enum_GameStep `protobuf:"varint,3,opt,name=gameStep,proto3,enum=pb_msg.Enum_GameStep" json:"gameStep,omitempty"`
	MinRaise             float64       `protobuf:"fixed64,4,opt,name=minRaise,proto3" json:"minRaise,omitempty"`
	ActivePos            int32         `protobuf:"varint,5,opt,name=activePos,proto3" json:"activePos,omitempty"`
	NextStepTs           int64         `protobuf:"varint,6,opt,name=nextStepTs,proto3" json:"nextStepTs,omitempty"`
	Pot                  float64       `protobuf:"fixed64,7,opt,name=pot,proto3" json:"pot,omitempty"`
	PublicCardKeys       []int32       `protobuf:"varint,8,rep,packed,name=publicCardKeys,proto3" json:"publicCardKeys,omitempty"`
	PlayerDatas          []*PlayerData `protobuf:"bytes,9,rep,name=playerDatas,proto3" json:"playerDatas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{10}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

func (m *RoomData) GetIsStepEnd() bool {
	if m != nil {
		return m.IsStepEnd
	}
	return false
}

func (m *RoomData) GetGameStep() Enum_GameStep {
	if m != nil {
		return m.GameStep
	}
	return Enum_GameStep_STEP_WAITING
}

func (m *RoomData) GetMinRaise() float64 {
	if m != nil {
		return m.MinRaise
	}
	return 0
}

func (m *RoomData) GetActivePos() int32 {
	if m != nil {
		return m.ActivePos
	}
	return 0
}

func (m *RoomData) GetNextStepTs() int64 {
	if m != nil {
		return m.NextStepTs
	}
	return 0
}

func (m *RoomData) GetPot() float64 {
	if m != nil {
		return m.Pot
	}
	return 0
}

func (m *RoomData) GetPublicCardKeys() []int32 {
	if m != nil {
		return m.PublicCardKeys
	}
	return nil
}

func (m *RoomData) GetPlayerDatas() []*PlayerData {
	if m != nil {
		return m.PlayerDatas
	}
	return nil
}

//--5 根据房间条件快速匹配一张牌桌
type QuickStartC2S struct {
	RoomInfo             *RoomInfo `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QuickStartC2S) Reset()         { *m = QuickStartC2S{} }
func (m *QuickStartC2S) String() string { return proto.CompactTextString(m) }
func (*QuickStartC2S) ProtoMessage()    {}
func (*QuickStartC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{11}
}

func (m *QuickStartC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuickStartC2S.Unmarshal(m, b)
}
func (m *QuickStartC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuickStartC2S.Marshal(b, m, deterministic)
}
func (m *QuickStartC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuickStartC2S.Merge(m, src)
}
func (m *QuickStartC2S) XXX_Size() int {
	return xxx_messageInfo_QuickStartC2S.Size(m)
}
func (m *QuickStartC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_QuickStartC2S.DiscardUnknown(m)
}

var xxx_messageInfo_QuickStartC2S proto.InternalMessageInfo

func (m *QuickStartC2S) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

//--6 创建房间请求
type CreateRoomC2S struct {
	RoomInfo             *RoomInfo `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateRoomC2S) Reset()         { *m = CreateRoomC2S{} }
func (m *CreateRoomC2S) String() string { return proto.CompactTextString(m) }
func (*CreateRoomC2S) ProtoMessage()    {}
func (*CreateRoomC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{12}
}

func (m *CreateRoomC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomC2S.Unmarshal(m, b)
}
func (m *CreateRoomC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomC2S.Marshal(b, m, deterministic)
}
func (m *CreateRoomC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomC2S.Merge(m, src)
}
func (m *CreateRoomC2S) XXX_Size() int {
	return xxx_messageInfo_CreateRoomC2S.Size(m)
}
func (m *CreateRoomC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomC2S.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomC2S proto.InternalMessageInfo

func (m *CreateRoomC2S) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

//--7 加入房间请求
type JoinRoomC2S struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomC2S) Reset()         { *m = JoinRoomC2S{} }
func (m *JoinRoomC2S) String() string { return proto.CompactTextString(m) }
func (*JoinRoomC2S) ProtoMessage()    {}
func (*JoinRoomC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{13}
}

func (m *JoinRoomC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomC2S.Unmarshal(m, b)
}
func (m *JoinRoomC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomC2S.Marshal(b, m, deterministic)
}
func (m *JoinRoomC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomC2S.Merge(m, src)
}
func (m *JoinRoomC2S) XXX_Size() int {
	return xxx_messageInfo_JoinRoomC2S.Size(m)
}
func (m *JoinRoomC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomC2S.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomC2S proto.InternalMessageInfo

func (m *JoinRoomC2S) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *JoinRoomC2S) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

//--8 进入房间
type EnterRoomS2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnterRoomS2C) Reset()         { *m = EnterRoomS2C{} }
func (m *EnterRoomS2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoomS2C) ProtoMessage()    {}
func (*EnterRoomS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{14}
}

func (m *EnterRoomS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomS2C.Unmarshal(m, b)
}
func (m *EnterRoomS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomS2C.Marshal(b, m, deterministic)
}
func (m *EnterRoomS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomS2C.Merge(m, src)
}
func (m *EnterRoomS2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoomS2C.Size(m)
}
func (m *EnterRoomS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomS2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomS2C proto.InternalMessageInfo

func (m *EnterRoomS2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

//--9 退出房间请求
type ExitRoomC2S struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitRoomC2S) Reset()         { *m = ExitRoomC2S{} }
func (m *ExitRoomC2S) String() string { return proto.CompactTextString(m) }
func (*ExitRoomC2S) ProtoMessage()    {}
func (*ExitRoomC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{15}
}

func (m *ExitRoomC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitRoomC2S.Unmarshal(m, b)
}
func (m *ExitRoomC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitRoomC2S.Marshal(b, m, deterministic)
}
func (m *ExitRoomC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitRoomC2S.Merge(m, src)
}
func (m *ExitRoomC2S) XXX_Size() int {
	return xxx_messageInfo_ExitRoomC2S.Size(m)
}
func (m *ExitRoomC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitRoomC2S.DiscardUnknown(m)
}

var xxx_messageInfo_ExitRoomC2S proto.InternalMessageInfo

func (m *ExitRoomC2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//--10 退出房间
type ExitRoomS2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ExitRoomS2C) Reset()         { *m = ExitRoomS2C{} }
func (m *ExitRoomS2C) String() string { return proto.CompactTextString(m) }
func (*ExitRoomS2C) ProtoMessage()    {}
func (*ExitRoomS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{16}
}

func (m *ExitRoomS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitRoomS2C.Unmarshal(m, b)
}
func (m *ExitRoomS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitRoomS2C.Marshal(b, m, deterministic)
}
func (m *ExitRoomS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitRoomS2C.Merge(m, src)
}
func (m *ExitRoomS2C) XXX_Size() int {
	return xxx_messageInfo_ExitRoomS2C.Size(m)
}
func (m *ExitRoomS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitRoomS2C.DiscardUnknown(m)
}

var xxx_messageInfo_ExitRoomS2C proto.InternalMessageInfo

func (m *ExitRoomS2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb_msg.Enum_SvrTipType", Enum_SvrTipType_name, Enum_SvrTipType_value)
	proto.RegisterEnum("pb_msg.Enum_CardKind", Enum_CardKind_name, Enum_CardKind_value)
	proto.RegisterEnum("pb_msg.Enum_CardSuit", Enum_CardSuit_name, Enum_CardSuit_value)
	proto.RegisterEnum("pb_msg.Enum_ActionOptions", Enum_ActionOptions_name, Enum_ActionOptions_value)
	proto.RegisterEnum("pb_msg.Enum_Blind", Enum_Blind_name, Enum_Blind_value)
	proto.RegisterEnum("pb_msg.Enum_GameStep", Enum_GameStep_name, Enum_GameStep_value)
	proto.RegisterEnum("pb_msg.Enum_PlayerStatus", Enum_PlayerStatus_name, Enum_PlayerStatus_value)
	proto.RegisterEnum("pb_msg.Enum_ActionTimeS", Enum_ActionTimeS_name, Enum_ActionTimeS_value)
	proto.RegisterType((*PingC2S)(nil), "pb_msg.Ping_c2s")
	proto.RegisterType((*PongS2C)(nil), "pb_msg.Pong_s2c")
	proto.RegisterType((*SvrMsgS2C)(nil), "pb_msg.SvrMsg_s2c")
	proto.RegisterType((*PlayerInfo)(nil), "pb_msg.PlayerInfo")
	proto.RegisterType((*LoginInfo)(nil), "pb_msg.LoginInfo")
	proto.RegisterType((*LoginC2S)(nil), "pb_msg.Login_c2s")
	proto.RegisterType((*LoginResultS2C)(nil), "pb_msg.LoginResult_s2c")
	proto.RegisterType((*CardSuitData)(nil), "pb_msg.CardSuitData")
	proto.RegisterType((*RoomInfo)(nil), "pb_msg.RoomInfo")
	proto.RegisterType((*PlayerData)(nil), "pb_msg.PlayerData")
	proto.RegisterType((*RoomData)(nil), "pb_msg.RoomData")
	proto.RegisterType((*QuickStartC2S)(nil), "pb_msg.QuickStart_c2s")
	proto.RegisterType((*CreateRoomC2S)(nil), "pb_msg.CreateRoom_c2s")
	proto.RegisterType((*JoinRoomC2S)(nil), "pb_msg.JoinRoom_c2s")
	proto.RegisterType((*EnterRoomS2C)(nil), "pb_msg.EnterRoom_s2c")
	proto.RegisterType((*ExitRoomC2S)(nil), "pb_msg.ExitRoom_c2s")
	proto.RegisterType((*ExitRoomS2C)(nil), "pb_msg.ExitRoom_s2c")
}

func init() { proto.RegisterFile("pb_msg.proto", fileDescriptor_bd13c7201b21be60) }

var fileDescriptor_bd13c7201b21be60 = []byte{
	// 1320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xdb, 0x46,
	0x13, 0x35, 0xa9, 0x3f, 0x6a, 0x24, 0xcb, 0xeb, 0xfd, 0xf2, 0x35, 0x6c, 0xd1, 0x06, 0x06, 0x51,
	0x14, 0x86, 0x50, 0x24, 0x88, 0x5b, 0xa0, 0x41, 0x91, 0x14, 0xa0, 0x24, 0xca, 0x62, 0x4c, 0x89,
	0xea, 0x92, 0x8a, 0xd3, 0x2b, 0x82, 0x16, 0x19, 0x85, 0xa8, 0x44, 0x0a, 0x24, 0xe5, 0xc6, 0xd7,
	0xbd, 0xea, 0x75, 0xfb, 0x0c, 0x7d, 0x8a, 0xbe, 0x45, 0x5f, 0xa8, 0x98, 0xe5, 0x8f, 0xa8, 0xc4,
	0xbd, 0x68, 0x6e, 0x84, 0x3d, 0x67, 0xcf, 0xcc, 0xec, 0xcc, 0xce, 0x0e, 0x05, 0xdd, 0xed, 0x8d,
	0xb3, 0x49, 0x56, 0x8f, 0xb7, 0x71, 0x94, 0x46, 0xb4, 0x99, 0x21, 0x05, 0x40, 0x9a, 0x07, 0xe1,
	0xca, 0x59, 0x5e, 0x24, 0x4a, 0x1f, 0xa4, 0x79, 0x14, 0xae, 0x9c, 0xe4, 0x62, 0x49, 0x1f, 0x01,
	0x24, 0x7e, 0x7c, 0xeb, 0xc7, 0x76, 0xb0, 0xf1, 0x65, 0xe1, 0x4c, 0x38, 0xaf, 0xb1, 0x0a, 0xa3,
	0xac, 0x00, 0xac, 0xdb, 0x78, 0x9a, 0x64, 0x6a, 0x0a, 0xf5, 0x65, 0xe4, 0x65, 0xba, 0x06, 0xe3,
	0x6b, 0xe4, 0x3c, 0x37, 0x75, 0x65, 0xf1, 0x4c, 0x38, 0x6f, 0x33, 0xbe, 0xa6, 0x4f, 0xa1, 0x95,
	0x06, 0x5b, 0xfb, 0x6e, 0xeb, 0xcb, 0xb5, 0x33, 0xe1, 0xbc, 0x77, 0xf1, 0xf0, 0x71, 0x7e, 0x2a,
	0x2d, 0xdc, 0x6d, 0x1c, 0xeb, 0x36, 0xb6, 0xb3, 0x6d, 0x56, 0xe8, 0x14, 0x0f, 0x60, 0xbe, 0x76,
	0xef, 0xfc, 0x58, 0x0f, 0xdf, 0x44, 0xb4, 0x07, 0x62, 0xe0, 0xf1, 0x30, 0x6d, 0x26, 0x06, 0x1e,
	0x06, 0x09, 0xdd, 0x8d, 0x5f, 0x04, 0xc1, 0x35, 0x95, 0xa1, 0xf5, 0xd6, 0x77, 0x3d, 0x7d, 0xb3,
	0xe2, 0x41, 0xda, 0xac, 0x80, 0xb8, 0x73, 0xe3, 0xae, 0xdd, 0x70, 0xe9, 0xcb, 0xf5, 0x33, 0xe1,
	0x5c, 0x60, 0x05, 0x54, 0x2c, 0x68, 0x1b, 0xd1, 0x2a, 0x08, 0xef, 0x0d, 0xf2, 0x10, 0x5a, 0x2b,
	0x77, 0xe3, 0x3b, 0x81, 0x97, 0xc7, 0x69, 0x22, 0xd4, 0x3d, 0xfa, 0x45, 0x51, 0x24, 0x67, 0x17,
	0xaf, 0xf3, 0x60, 0xed, 0x8c, 0x59, 0xc4, 0x6b, 0xe5, 0x79, 0xee, 0x14, 0x8b, 0x4b, 0x9f, 0x40,
	0x7b, 0x5d, 0x44, 0xe0, 0xbe, 0x3b, 0x17, 0xa7, 0x45, 0xf2, 0x65, 0x68, 0xb6, 0xd7, 0x28, 0x1a,
	0x9c, 0x70, 0x9e, 0xf9, 0xc9, 0x6e, 0x9d, 0xf2, 0x32, 0x5f, 0x00, 0x6c, 0xcb, 0x5a, 0xe4, 0x4e,
	0x68, 0xe1, 0x64, 0x5f, 0x25, 0x56, 0x51, 0x29, 0xbf, 0x0b, 0xd0, 0x1d, 0xba, 0xb1, 0x67, 0xed,
	0x82, 0x74, 0x84, 0x77, 0xa0, 0x40, 0xf7, 0xad, 0x1b, 0x7a, 0xc8, 0x5d, 0xf9, 0x77, 0x89, 0x2c,
	0x9c, 0xd5, 0xce, 0x1b, 0xec, 0x80, 0xa3, 0x5f, 0x41, 0x6f, 0xbb, 0xbb, 0x59, 0x07, 0xcb, 0x52,
	0x25, 0x72, 0xd5, 0x7b, 0x2c, 0xfd, 0x0e, 0x3a, 0xc9, 0x2e, 0x48, 0xe7, 0x6e, 0x9a, 0xfa, 0x71,
	0x98, 0xdf, 0xe9, 0xff, 0x0f, 0xee, 0xb4, 0x88, 0xcd, 0xaa, 0x4a, 0xe5, 0x4f, 0x01, 0x24, 0x16,
	0x45, 0x1b, 0x5e, 0xef, 0x4f, 0xa0, 0x19, 0xe3, 0xba, 0xa8, 0x79, 0x8e, 0xe8, 0x03, 0x68, 0x2c,
	0xdf, 0xac, 0xf4, 0xa2, 0xea, 0x19, 0xa0, 0x9f, 0x43, 0x7b, 0xe3, 0xbe, 0xcb, 0xb2, 0xe5, 0x11,
	0x1b, 0x6c, 0x4f, 0xd0, 0xe7, 0xd0, 0x75, 0x97, 0x69, 0x10, 0x85, 0xd8, 0xa5, 0x4e, 0xc2, 0xef,
	0xb9, 0x77, 0xf1, 0xe9, 0xc1, 0x91, 0xd4, 0x8a, 0x80, 0x75, 0xf6, 0x72, 0x8b, 0x12, 0xa8, 0x6d,
	0x7f, 0xf1, 0xe4, 0x06, 0x8f, 0x87, 0x4b, 0xe5, 0xb7, 0x7a, 0xd1, 0x7f, 0xbc, 0x78, 0x1f, 0x71,
	0x03, 0xf4, 0x33, 0x90, 0xb6, 0x51, 0x12, 0x60, 0x14, 0x9e, 0x49, 0x83, 0x95, 0x18, 0xf7, 0x82,
	0x84, 0xb9, 0x41, 0xe2, 0x7b, 0x3c, 0x17, 0x89, 0x95, 0x98, 0xbe, 0x80, 0x6e, 0xe6, 0xc5, 0x4a,
	0xdd, 0x74, 0x77, 0x7f, 0x2a, 0xf3, 0x8a, 0x80, 0x1d, 0xc8, 0xf1, 0x05, 0x7b, 0x71, 0xb4, 0xf5,
	0xbd, 0x81, 0x9f, 0x26, 0x3c, 0x25, 0x81, 0x55, 0x18, 0xfa, 0x25, 0x1c, 0xef, 0x91, 0xb5, 0xdb,
	0xc8, 0x4d, 0x2e, 0x39, 0x24, 0xf1, 0x80, 0xcb, 0xa2, 0x07, 0x5a, 0xbc, 0x07, 0x4a, 0x4c, 0x9f,
	0x41, 0x77, 0x59, 0xe9, 0x2c, 0x59, 0xe2, 0xe5, 0x78, 0x50, 0x1c, 0xb0, 0xda, 0x75, 0xec, 0x40,
	0x99, 0xa5, 0x7d, 0x1d, 0x84, 0xa1, 0x1f, 0xcb, 0xed, 0x22, 0xed, 0x0c, 0xd3, 0x73, 0x68, 0xdc,
	0xac, 0x83, 0xd0, 0x93, 0x81, 0xe7, 0x4b, 0x0f, 0xf2, 0x1d, 0xe0, 0x0e, 0xcb, 0x04, 0x99, 0x97,
	0xc1, 0x2e, 0x4d, 0xa3, 0x50, 0xee, 0x14, 0x5e, 0x32, 0x8c, 0x4f, 0x3d, 0x48, 0xd4, 0xf5, 0x5a,
	0x0f, 0xe5, 0x2e, 0xdf, 0x2a, 0x20, 0x76, 0x5b, 0x90, 0x58, 0xfe, 0xfa, 0x8d, 0x7c, 0xcc, 0x37,
	0x72, 0x44, 0xcf, 0xa0, 0x13, 0xf3, 0xa7, 0x36, 0x8d, 0x42, 0xff, 0x4e, 0xee, 0xf1, 0x6a, 0x54,
	0x29, 0xe5, 0x6f, 0x31, 0x6b, 0x5a, 0x9e, 0xc2, 0xd7, 0x20, 0xc5, 0x79, 0x03, 0xe7, 0x7d, 0x40,
	0x8a, 0x93, 0x16, 0x8d, 0xcd, 0x4a, 0x05, 0x36, 0x6d, 0x90, 0x58, 0xa9, 0xbf, 0xd5, 0xc2, 0xac,
	0x9d, 0x25, 0xb6, 0x27, 0xe8, 0x53, 0x90, 0x70, 0xa2, 0x20, 0xbc, 0xf7, 0x0d, 0x5d, 0xe6, 0x9b,
	0xac, 0x94, 0x61, 0xee, 0x9b, 0x20, 0xe4, 0x9d, 0x92, 0xcf, 0xb2, 0x12, 0x63, 0x30, 0x6c, 0xea,
	0x5b, 0x7f, 0x1e, 0x65, 0x17, 0xdf, 0x60, 0x7b, 0x02, 0xfb, 0x22, 0xf4, 0xdf, 0xa5, 0xe8, 0xc5,
	0x4e, 0xf8, 0xa5, 0xd7, 0x58, 0x85, 0xe1, 0x6f, 0x20, 0x4a, 0xe5, 0x16, 0x77, 0x8a, 0xcb, 0x7b,
	0xa6, 0x81, 0x74, 0xef, 0x34, 0xf8, 0x16, 0x3a, 0xdb, 0xf2, 0xa9, 0x24, 0x72, 0xfb, 0xac, 0xf6,
	0xe1, 0xeb, 0xe0, 0xcd, 0x50, 0x95, 0x29, 0x3f, 0x40, 0xef, 0xc7, 0x5d, 0xb0, 0xfc, 0xd9, 0x4a,
	0xdd, 0x38, 0xe5, 0xa3, 0xf2, 0x3f, 0x95, 0x16, 0xed, 0x87, 0xb1, 0xef, 0xa6, 0x3e, 0xee, 0x7d,
	0x84, 0xfd, 0x33, 0xe8, 0xbe, 0x8c, 0x82, 0xb0, 0xb4, 0xfe, 0xb7, 0x69, 0x94, 0xcf, 0x06, 0x71,
	0x3f, 0x1b, 0x5e, 0xc0, 0xb1, 0x16, 0xa6, 0x7e, 0xcc, 0x4d, 0x71, 0x3e, 0xe7, 0x81, 0xf9, 0x63,
	0xb8, 0x27, 0x30, 0xcf, 0xbd, 0x54, 0x28, 0x8f, 0xa0, 0xab, 0xbd, 0x0b, 0xd2, 0x32, 0x70, 0x0f,
	0xc4, 0x32, 0xa8, 0xa8, 0x7b, 0xca, 0xa0, 0xb2, 0xff, 0x91, 0xd3, 0xbf, 0xff, 0x04, 0x4e, 0xde,
	0xfb, 0xb2, 0xd2, 0x16, 0xd4, 0xa6, 0xd6, 0x25, 0x39, 0xa2, 0x12, 0xd4, 0xaf, 0x55, 0x36, 0x23,
	0x02, 0x6d, 0x43, 0x43, 0x63, 0xcc, 0x64, 0x44, 0xec, 0x5f, 0x62, 0x4e, 0xf9, 0xd8, 0xbe, 0xc2,
	0x47, 0x26, 0x41, 0x7d, 0x66, 0xce, 0x34, 0x72, 0x44, 0x3b, 0xd0, 0x1a, 0xe9, 0xea, 0xd4, 0x9c,
	0x8d, 0x32, 0x93, 0xa1, 0xb1, 0x18, 0x58, 0x44, 0xc4, 0xe5, 0x44, 0x53, 0x99, 0x4d, 0x6a, 0xb8,
	0xb4, 0xe6, 0xea, 0x48, 0x23, 0xf5, 0xfe, 0x5f, 0x42, 0xc5, 0x13, 0x3e, 0x7c, 0xee, 0x69, 0x61,
	0x18, 0xe4, 0x88, 0x1e, 0x43, 0x7b, 0xa2, 0x5f, 0x4e, 0x9c, 0xa1, 0xca, 0xd0, 0x57, 0x17, 0x24,
	0x73, 0xa6, 0x39, 0x73, 0x55, 0x67, 0x44, 0xc4, 0x4d, 0xfb, 0xda, 0xe4, 0xc8, 0x22, 0x35, 0xfa,
	0x3f, 0x38, 0xb1, 0x27, 0x4c, 0xd3, 0x1c, 0x73, 0xec, 0xa8, 0xce, 0x95, 0x3e, 0x1b, 0x91, 0x3a,
	0x5a, 0x58, 0x36, 0x53, 0xf5, 0xcb, 0x89, 0x4d, 0x1a, 0x18, 0x75, 0x6c, 0x2c, 0xac, 0x09, 0x69,
	0xd2, 0x1e, 0xc0, 0x78, 0x61, 0x18, 0xce, 0xc4, 0x5c, 0x58, 0x1a, 0x69, 0x51, 0x0a, 0xbd, 0xb1,
	0xb9, 0x60, 0x15, 0x63, 0x09, 0xb9, 0xc2, 0xd8, 0xc9, 0xec, 0xda, 0xf4, 0x04, 0x3a, 0xcc, 0xfc,
	0x49, 0x35, 0x72, 0x02, 0xfa, 0x7f, 0x08, 0x40, 0x2b, 0x1f, 0x0b, 0x73, 0x8b, 0xbf, 0x09, 0x3d,
	0x85, 0x63, 0x75, 0x68, 0x3b, 0x2f, 0x4d, 0x7d, 0xe6, 0x30, 0xd3, 0x9c, 0x66, 0x65, 0x41, 0xca,
	0xd2, 0x6d, 0x22, 0x50, 0x02, 0x5d, 0x0e, 0x6c, 0x75, 0x36, 0x72, 0x16, 0x73, 0x22, 0x62, 0x34,
	0x64, 0x0c, 0x4d, 0x7d, 0xa5, 0x65, 0x26, 0x35, 0x3c, 0x3e, 0x72, 0x63, 0xd3, 0xc8, 0x93, 0x41,
	0x34, 0x54, 0x0d, 0x83, 0x34, 0x30, 0x7d, 0x44, 0x4c, 0xd5, 0x2d, 0x8d, 0x34, 0x0b, 0x38, 0x9c,
	0x68, 0xc3, 0x2b, 0xd2, 0xea, 0x7f, 0x0f, 0xb0, 0x9f, 0x83, 0x68, 0x39, 0x33, 0x9d, 0x81, 0x81,
	0x79, 0x1d, 0x61, 0x0e, 0xd6, 0x54, 0x35, 0x8c, 0x9c, 0x10, 0xd0, 0x76, 0xa0, 0x5f, 0xe6, 0x50,
	0xec, 0xdf, 0xe6, 0x17, 0x52, 0x4c, 0x13, 0x3c, 0xac, 0x65, 0x6b, 0x73, 0xe7, 0x5a, 0xd5, 0x6d,
	0x7d, 0x86, 0x2d, 0x71, 0x0a, 0xc7, 0x9c, 0x99, 0x33, 0xcd, 0x19, 0x1b, 0xe6, 0x3c, 0x73, 0xc2,
	0x29, 0x0e, 0xc5, 0x12, 0xda, 0x0b, 0x36, 0x23, 0x35, 0xac, 0x37, 0x87, 0x4c, 0x7f, 0xa5, 0x31,
	0x52, 0xcf, 0x6a, 0xab, 0xcd, 0x1d, 0x6b, 0x62, 0x5e, 0x3b, 0x23, 0xf3, 0x7a, 0x46, 0x1a, 0xfd,
	0x5f, 0x05, 0x38, 0xfd, 0xe0, 0x63, 0x95, 0x29, 0x55, 0x7b, 0x61, 0x55, 0xc2, 0xf3, 0x03, 0x71,
	0x2e, 0x4b, 0x5f, 0xe0, 0x39, 0x65, 0x0c, 0x2f, 0x8f, 0x58, 0x91, 0x64, 0x25, 0xa9, 0x55, 0x24,
	0x79, 0x3d, 0x1f, 0x00, 0xc9, 0x89, 0xea, 0x29, 0x2e, 0xf2, 0x43, 0x54, 0x3f, 0xfe, 0xf8, 0x16,
	0x5e, 0xbf, 0x7e, 0x4d, 0x8e, 0x28, 0x40, 0x73, 0x66, 0xb2, 0xa9, 0x6a, 0x90, 0x13, 0xec, 0xd3,
	0xb1, 0x6a, 0xd9, 0x04, 0x6e, 0x9a, 0xfc, 0xbf, 0xf2, 0x37, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0xc8, 0x53, 0xab, 0x3b, 0x0b, 0x00, 0x00,
}
